### ISSUE TITLE
Tasks: Completion bugs

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#252] opened 2017-01-21 11:12 UTC
https://forums.bistudio.com/topic/187954-alive-advanced-light-infantry-virtual-environment-10-ga/?do=findComment&comment=3142828

If the task says I need to kill the HVT, I kill him, but the task remains active. 

The Hostage Rescue Task will not complete even when transporting the Hostage back to the designated location.
 
The Pick up troops task will not 'FAIL' even when all of the troops that are set to be collected are killed in action (happened today).  Just remained ACTIVE.
 
Destroy the Vehicle task is hit or miss (pun intended), destroyed the vehicle or vehicles and not end task (used debug to search for a possible missed vehicle...nothing.

**Comment by highhead** [comment] 2017-01-21 15:47
Needs repro in vanilla!

Tested today.

HVT mission completing in SP - check
Hostage rescue mission completing in SP - check
Destroy vehicles mission completing in SP - check

HVT mission completing on dedi - check
Hostage rescue mission completing on dedi - check
Destroy vehicles mission completing on dedi - check

Pickup troops untested!

I am getting desync on task completion since all tasks have to be synced across the network but no "bad lag" or freezes (e.g. server drops to below 10 FPS). I will split those tickets.

**Comment by AshEdwardsDesign** [comment] 2017-08-06 14:53
Just adding my own observation to this, as I had a completion bug with the "Pickup troops" mission, auto assigned by OPCOM.

So, I received the mission to pick up some troops (objective 1) and drop them off at another location (objective 2).

After several minutes, I got the notification that I had failed (presumably the troops in question had been killed). So objective 1 was marked as failed, however objective 2 was still shown as assigned. I had to go into the Tasks menu on the tablet and cancel the mission manually.

Sorry but I cannot remember if OPCOM assigned another task to me after the objective 1 failure or whether it waited until after I had manually cancelled the task.

This was running just CBA_A3 and ALiVE (both from Steam workshop).

I will try and reproduce if I can.

**Comment by tupolov** [comment] 2017-09-06 22:26
Tested pickup troops on SP and works ok. Noticed an issue with the first pickup child task, sometimes it doesn't complete.

Can see that child tasks don't get cancelled if others fail too.

**Comment by highhead** [comment] 2017-10-27 13:47
Found some issues when testing all tasks and fixed them. They were related to JIP option not set in remoteExec command. All tasks have now been tested in SP and MP (hosted).

Note the following known issues (for some of them I am going to set up separate tickets):

- For the Offensive Counter Air task you need to destroy at least 3 buildings around a runway or helipad
- Insurgeny tasks will only work with insurgency enabled
- The Capture Objective task should not be called via cmdrs tablet atm. (https://github.com/ALiVEOS/ALiVE.OS/issues/456), it will not create a task at all though
- If a mission fails and there are several child tasks only one child task is updated. This does not affect failing & succeding though (https://github.com/ALiVEOS/ALiVE.OS/issues/458).

**Closed by highhead** 2017-10-27 13:47 UTC
Labels: bug, C2ISTAR, Ready

**Comment by highhead** [comment] 2017-10-27 13:50
For new task bugs please provide the following data:

- which mission
- which factions used
- if generated via cmdrs tablet then the options which were used
- SP / DEDI / HOSTED?
- Did the player which saw the issue JIP or has the player been killed before
