### ISSUE TITLE
Player Resupply issues

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#376] opened 2017-06-27 18:22 UTC
Couple of issues reported.  Need investigation and repro:

Logistics whitelists seem to be broken I have B_supplyCrate_F,rhsusf_m1025_d_Mk19, in white list option but it drops a random metal crate not the supply box nato

Logistics appears to be completely non functional on dedi servers

**Comment by flibble666** [comment] 2017-06-27 22:20
Hello it was me who posted on steam here is the RPT please note this was run locally non dedicated i can host it on a dedicated machine and re test and with less mods etc if required.

[RPT](https://pastebin.com/1vxpv80m)

**Comment by HeroesandvillainsOS** [comment] 2017-06-28 01:52
I can confirm some weirdness with the whitelist option. ALiVE CBA only. I whitelisted Box_NATO_Ammo_F and although it was listed as the only logistics object available, they sent me B_CargoNet_01_ammo_F.

Server rpt if it helps: https://www.dropbox.com/s/phq5sm7ymcsxeg9/arma3server_x64_2017-06-27_20-58-46.rpt?dl=0

Bare in mind, I did not test whether this incorrect object is still delivered when requesting the item without using the whitelist option. So I guess it's possible whitelisting has nothing to do with wrong items being delivered.

**Comment by GunnyDev** [comment] 2017-06-28 12:06
Closing the ticket, this is not a bug. All items requested via Para Drop are sent within a default continer based on faction. You will need to use Player Logistics to unload the requested items.

**Closed by GunnyDev** 2017-06-28 12:06 UTC
Labels: bug

**Comment by flibble666** [comment] 2017-06-28 14:15
I have tested with all NATO factions and i still get random boxes instead of ones in white list B_supplyCrate_F in whit list drops CargoNet_01_box_F instead NATO factions only ace3,tfar,cba,alive loaded no modded factions. this was defiantly not the case before the last update as i had a cba script on the same mission that droped the B_supplyCrate_F with arsenal attached now its different every time

**Comment by highhead** [comment] 2017-06-28 17:04
You do understand, that the container or crate, which is dropped via parachute or unloaded near the transport vehicles, needs to be walked up to and the "unload cargo" action (mousewheel) needs to be clicked to eventually make the appropriate cargo (that you selected before to be dropped) been unloaded? You therefore may need to activate the player logistics actions via ALiVE menu.

The Whitelist is not for selecting the container-box which is brought by the transportvehicles but for the cargo which can be selected.

**Comment by flibble666** [comment] 2017-06-28 17:14
yer sorry understood now my apologise.

**Comment by highhead** [comment] 2017-06-28 17:16
please report back if you still have questions! I am trying to see what is up with that cargo net being delivered as it sounds weird

**Comment by highhead** [comment] 2017-06-28 17:23
i mixed that up when reading... its not a cargo net but a cargonet box. thats fine.

**Comment by GunnyDev** [comment] 2017-06-28 18:34
I added code, so that all the extra stuff that comes as default it the container is cleared out prior to loading it with the requested items.
