### ISSUE TITLE
ORBAT created unit not showing up with helmets, maps (occasionally), NVG's and a few other items.

### ISSUE THREAD

**Issue by coachwn** [ALiVEOS/ALiVE.OS#155] opened 2016-11-09 22:26 UTC
As a result of working on issue #153 ; I have now located another bug. The helmet which is bolded below is not showing up on any Rifleman in the different groups. No other units are showing helmets or headgear of any type. 

Why would that be the issue there with the AI units but not the units that the player(s) can be in?

class O_SHGPLA_SHG_PLA_Rifleman : O_T_Soldier_F_OCimport_02 {
        author = "Nichols";
        scope = 2;
        scopeArsenal = 2;
        displayName = "SHG PLA Rifleman";
        side = 0;
        faction = "SHG_PLA";

        identityTypes[] = { "Head_Asian" , "LanguageCHI_F" , "G_CIVIL_male" };
        uniformClass = "PLA_CombatUniform_SG";
        backpack = "PLA_AssaultPack_Base";

        linkedItems[] = { "ItemMap" , "ItemCompass" , "ItemWatch" , "tf_fadak" , "ItemGPS" , "NVGoggles_mas_h" , "Rangefinder" , "PLA_T15Vest_RD" , "**VME_PLA_Helmet_R**" };
        weapons[] = { "vme_pla_qbz03" , "vme_pla_qsw06" , "Rangefinder" , "Throw" , "Put" };
        magazines[] = { "Chemlight_yellow" , "Chemlight_red" , "SmokeShellGreen" , "SmokeShellRed" , "HandGrenade" , "HandGrenade" , "1Rnd_HE_Grenade_shell" , "1Rnd_HE_Grenade_shell" , "1Rnd_HE_Grenade_shell" , "1Rnd_HE_Grenade_shell" , "1Rnd_HE_Grenade_shell" , "1Rnd_Smoke_Grenade_shell" , "1Rnd_SmokeRed_Grenade_shell" , "1Rnd_SmokeGreen_Grenade_shell" , "1Rnd_SmokeYellow_Grenade_shell" , "1Rnd_SmokePurple_Grenade_shell" , "O_IR_Grenade" , "O_IR_Grenade" , "VME_QSZ92_20Rnd_DAP92" , "VME_QSZ92_20Rnd_DAP92" , "VME_QBZ95_1_30Rnd_DBP87" , "VME_QBZ95_1_30Rnd_DBP87" , "VME_QBZ95_1_30Rnd_DBP87" , "VME_1Rnd_HE_GL" , "VME_1Rnd_HE_GL" , "VME_1Rnd_HE_GL" , "VME_1Rnd_HE_GL" , "VME_1Rnd_HE_GL" , "VME_1Rnd_HE_GL" , "VME_1Rnd_HE_GL" , "VME_1Rnd_HE_GL" , "VME_1Rnd_HE_GL" , "VME_1Rnd_Smoke_GL" , "VME_1Rnd_Smoke_GL" };

        respawnLinkedItems[] = { "ItemMap" , "ItemCompass" , "ItemWatch" , "tf_fadak" , "ItemGPS" , "NVGoggles_mas_h" , "Rangefinder" , "PLA_T15Vest_RD" , "**VME_PLA_Helmet_R**" };
        respawnWeapons[] = { "vme_pla_qbz03" , "vme_pla_qsw06" , "Rangefinder" , "Throw" , "Put" };
        respawnMagazines[] = { "Chemlight_yellow" , "Chemlight_red" , "SmokeShellGreen" , "SmokeShellRed" , "HandGrenade" , "HandGrenade" , "1Rnd_HE_Grenade_shell" , "1Rnd_HE_Grenade_shell" , "1Rnd_HE_Grenade_shell" , "1Rnd_HE_Grenade_shell" , "1Rnd_HE_Grenade_shell" , "1Rnd_Smoke_Grenade_shell" , "1Rnd_SmokeRed_Grenade_shell" , "1Rnd_SmokeGreen_Grenade_shell" , "1Rnd_SmokeYellow_Grenade_shell" , "1Rnd_SmokePurple_Grenade_shell" , "O_IR_Grenade" , "O_IR_Grenade" , "VME_QSZ92_20Rnd_DAP92" , "VME_QSZ92_20Rnd_DAP92" , "VME_QBZ95_1_30Rnd_DBP87" , "VME_QBZ95_1_30Rnd_DBP87" , "VME_QBZ95_1_30Rnd_DBP87" , "VME_1Rnd_HE_GL" , "VME_1Rnd_HE_GL" , "VME_1Rnd_HE_GL" , "VME_1Rnd_HE_GL" , "VME_1Rnd_HE_GL" , "VME_1Rnd_HE_GL" , "VME_1Rnd_HE_GL" , "VME_1Rnd_HE_GL" , "VME_1Rnd_HE_GL" , "VME_1Rnd_Smoke_GL" , "VME_1Rnd_Smoke_GL" };

        class EventHandlers : EventHandlers {
            

            class ALiVE_orbatCreator {
                init = "_unit = (_this select 0);_unit setUnitLoadout [[],[],[],[],[],[],'','',[],['','','','','','']];_unit forceAddUniform 'PLA_CombatUniform_SG';_unit addVest 'PLA_T15Vest_RD';_unit addBackpack 'PLA_AssaultPack_Base';{_unit removeItemFromUniform _x} foreach (uniformItems _unit);{_unit removeItemFromVest _x} foreach (vestItems _unit);{_unit removeItemFromBackpack _x} foreach (backpackItems _unit);_unit addItemToUniform 'acc_flashlight';for '_i' from 1 to 4 do {_unit addItemToUniform 'ACE_fieldDressing';};for '_i' from 1 to 2 do {_unit addItemToUniform 'ACE_morphine';};for '_i' from 1 to 4 do {_unit addItemToUniform 'ACE_elasticBandage';};for '_i' from 1 to 2 do {_unit addItemToUniform 'ACE_epinephrine';};for '_i' from 1 to 4 do {_unit addItemToUniform 'ACE_packingBandage';};_unit addItemToUniform 'ACE_MapTools';_unit addItemToUniform 'ACE_Flashlight_XL50';_unit addItemToUniform 'ACE_EarPlugs';_unit addItemToUniform 'Chemlight_yellow';_unit addItemToUniform 'Chemlight_red';_unit addItemToVest 'SmokeShellGreen';_unit addItemToVest 'SmokeShellRed';for '_i' from 1 to 2 do {_unit addItemToVest 'HandGrenade';};for '_i' from 1 to 5 do {_unit addItemToVest '1Rnd_HE_Grenade_shell';};_unit addItemToVest '1Rnd_Smoke_Grenade_shell';_unit addItemToVest '1Rnd_SmokeRed_Grenade_shell';_unit addItemToVest '1Rnd_SmokeGreen_Grenade_shell';_unit addItemToVest '1Rnd_SmokeYellow_Grenade_shell';_unit addItemToVest '1Rnd_SmokePurple_Grenade_shell';for '_i' from 1 to 2 do {_unit addItemToVest 'O_IR_Grenade';};for '_i' from 1 to 2 do {_unit addItemToVest 'VME_QSZ92_20Rnd_DAP92';};for '_i' from 1 to 3 do {_unit addItemToVest 'VME_QBZ95_1_30Rnd_DBP87';};for '_i' from 1 to 9 do {_unit addItemToBackpack 'VME_1Rnd_HE_GL';};for '_i' from 1 to 2 do {_unit addItemToBackpack 'VME_1Rnd_Smoke_GL';};_unit addWeapon 'vme_pla_qbz03';_unit addWeapon 'vme_pla_qsw06';_unit addWeapon 'Rangefinder';_unit addPrimaryWeaponItem 'VME_Eotech_557_Magnifier_DOWN';_unit addPrimaryWeaponItem 'VME_QBZ03_rail';reload _unit;";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

**Comment by SpyderBlack723** [comment] 2016-11-09 22:35
Not a bug, rather a design decision due to how A3 handles headgear configs.

> Unfortunately, headgear in A3 is restricted to certain factions....
> 
> Nothing I can do about it other than add a completely new headgear class for each unit wearing a restricted headgear piece (Which adds a whole lot of clutter and extra complexity)

**Comment by coachwn** [comment] 2016-11-09 22:37
Also AI that is supposed to have map and compass has nothing showing up other than what is in vest and backpack. Is that to be expected as well?

**Comment by SpyderBlack723** [comment] 2016-11-09 22:38
No, but I know exactly why it doesn't save, and will fix that.

**Comment by coachwn** [comment] 2016-11-09 22:41
OK so Radios, maps, map tools, flash lights, nvg's etc...

Without those types of items my player insurgents are not going to be able to have a bunch of fun tracking down the AI and killing them.

**Comment by SpyderBlack723** [comment] 2016-11-11 01:52
Fixed with c62679849e5bf286833adf3eb0261e43e6bc07d2

Helmets not showing up when assigned to a restricted faction is a limitation of A3 and not exporting completely new helmet classes is a design decision due to the mess it would create. It can be requested in the feature request thread though (that doesn't mean it will make it in, or soon if it does)

**Closed by SpyderBlack723** 2016-11-11 01:52 UTC
