### ISSUE TITLE
Something is overwriting data in the profile system

### ISSUE THREAD

**Issue by marceldev89** [ALiVEOS/ALiVE.OS#564] opened 2018-11-21 16:45 UTC
This issue servers to track various issues related to data in the profile system being overwritten.

#### ~Vehicles assignment data is overwritten and no longer an array...~
```
2018/08/13, 14:51:52 Error in expression <+(_vehAssignment param [2, [], [[]]]);

reverse _unitAssignments; 

{
{
[_comman>
2018/08/13, 14:51:52   Error position: <reverse _unitAssignments; 

{
{
[_comman>
2018/08/13, 14:51:52   Error reverse: Type Number,Not a Number, expected Array
2018/08/13, 14:51:52 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2670
```

#### `_isPlayer` is somehow overwritten and no longer a boolean...
```
14:59:02 Error in expression <rgo = true;
};



if (!_vehicleCargo && !_isPlayer && !_isAir && !_combat) then >
14:59:02   Error position: <!_isPlayer && !_isAir && !_combat) then >
14:59:02   Error !: Type Number, expected Bool
14:59:02 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 1917
14:59:02 Error in expression <rgo = true;
};



if (!_vehicleCargo && !_isPlayer && !_isAir && !_combat) then >
14:59:02   Error position: <!_isPlayer && !_isAir && !_combat) then >
14:59:02   Error Generic error in expression
14:59:02 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 1917
14:59:05 Error in expression <isnil "_vehicle" && {(_vehicle select 2 select 15)} && {(_vehicle select 2 selec>
14:59:05   Error position: <select 15)} && {(_vehicle select 2 selec>
14:59:05   Error Type String, expected Bool
14:59:05 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 1902
14:59:05 Error in expression <cle" && {(_vehicle select 2 select 15)} && {(_vehicle select 2 select 11) isKind>
14:59:05   Error position: <&& {(_vehicle select 2 select 11) isKind>
14:59:05   Error &&: Type String, expected Bool
14:59:05 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 1902
```

**Comment by DavisBrown723** [comment] 2018-12-15 05:30
If we can get / have a repro mission for this error that would be immensely helpful as we could begin to remove systems one-by-one to narrow down the causes.

**Comment by diveyez** [comment] 2019-02-28 10:15
Its a problem with ALiVE and the current arma version.
I too noticed this tonight, profileSimulator keeps breaking

0 In marker expected 3 contiuously shows.

**Comment by diveyez** [comment] 2019-02-28 10:17
Using tablet to profile unprofiled units fixes it for about fifteen minutes. This is a major bug and needs patching ASAP. Why is that NOT an Array when it is expected by the engine to be?

**Comment by marceldev89** [comment] 2019-03-18 17:03
The vehicle assignment one has been fixed with https://github.com/ALiVEOS/ALiVE.OS/commit/5c35ff0e78365903c49c02b6e2b2a0b873bb0c74. Not entirely sure _why_ `_vehAssignments` would be empty while it apparently shouldn't be but at least the error won't be showing up anymore. :)

**Comment by MeltedPixel** [comment] 2020-02-07 18:20
Old ticket, Fixed via https://github.com/ALiVEOS/ALiVE.OS/commit/5c35ff0e78365903c49c02b6e2b2a0b873bb0c74

**Closed by MeltedPixel** 2020-02-07 18:20 UTC
Labels: Needs Repro, Profiles, bug
