### ISSUE TITLE
Logistics does not init correctly, data fails to load due to persistent roadblock incompatibility

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#261] opened 2017-01-22 06:13 UTC
aliveserver plugin: https://www.dropbox.com/s/cjc1s9quhsbr0g4/persistent_data_fail_aliveplugin_2017-01-22_00-54.txt?dl=0
server rpt: https://www.dropbox.com/s/13fifn2vsixqwp2/persistent_data_fail.rpt?dl=0

Possibly related to Logistics conflicting with the new Real Weather feature, according to @tupolov, when I reported a similar issue before the last update.

**Comment by HeroesandvillainsOS** [comment] 2017-01-22 16:08
If you guys want I can try to put a CBA ALiVE only repro together. The only reason I didn't is because I'm pretty sure this is being caused by something Tupolov already is aware of, but I'm not sure.

**Comment by tupolov** [comment] 2017-01-24 12:48
Looking at the logs, couple of things.

```Error in expression <call ALIVE_fnc_restore);
_i = _i + 1;
} forEach _value;

;
};
default {
_data = >
  Error position: <forEach _value;

;
};
default {
_data = >
  Error foreach: Type String, expected Array
File x\alive\addons\sys_data_couchdb\fnc_restoreData.sqf, line 106```

I've tried to resolve this with the following commit https://github.com/ALiVEOS/ALiVE.OS/commit/610a34ea7f6e0dc3220d746a61dbe7e93b1858c9

There appears to be issues with Logistics, so gonna pass to @highhead 

Looks like the foxhound data is loaded ok:

``` ------------------ Inspecting Hash -------------------- 
   k: burnes_foxhound_d_a_438018097
     k [0]: ALiVE_SYS_LOGISTICS_ID v: burnes_foxhound_d_a_438018097
     k [1]: ALiVE_SYS_LOGISTICS_TYPE v: burnes_foxhound_d_a
     k [2]: ALiVE_SYS_LOGISTICS_POSITION v: [10954.7,17946.3,0.0216064]
     k [3]: ALiVE_SYS_LOGISTICS_VECDIRANDUP v: [[0.521606,0.850259,-0.0706177],[0.064358,0.0433225,0.996986]]
     k [4]: ALiVE_SYS_LOGISTICS_CARGO v: [[],[],[],[[[],[]],[["30Rnd_556x45_Stanag","200Rnd_65x39_cased_Box","HandGrenade","1Rnd_HE_Grenade_shell","9Rnd_45ACP_Mag"],[16,3,10,10,12]],[["FirstAidKit"],[10]]],[]]
     k [5]: ALiVE_SYS_LOGISTICS_FUEL v: 0.945506
     k [6]: ALiVE_SYS_LOGISTICS_DAMAGE v: 0
     k [7]: _rev v: 1-69cec07c0ed061ecc7af1fea15193370```

But then we get:

```ALiVE_fnc_HashGet retrieved wrong input [["#CBA_HASH#",["burnes_foxhound_d_a_438018097"],[["#CBA_HASH#",["ALiVE_SYS_LOGISTICS_ID","ALiVE_SYS_LOGISTICS_TYPE","ALiVE_SYS_LOGISTICS_POSITION","ALiVE_SYS_LOGISTICS_VECDIRANDUP","ALiVE_SYS_LOGISTICS_CARGO","ALiVE_SYS_LOGISTICS_FUEL","ALiVE_SYS_LOGISTICS_DAMAGE","_rev"],["burnes_foxhound_d_a_438018097","burnes_foxhound_d_a",[10954.7,17946.3,0.0216064],[[0.521606,0.850259,-0.0706177],[0.064358,0.0433225,0.996986]],[[],[],[],[[[],[]],[["30Rnd_556x45_Stanag","200Rnd_65x39_cased_Box","HandGrenade","1Rnd_HE_Grenade_shell","9Rnd_45ACP_Mag"],[16,3,10,10,12]],[["FirstAidKit"],[10]]],[]],0.945506,0,"1-69cec07c0ed061ecc7af1fea15193370"],any]],any],<null>] from ALiVE_fnc_logistics!```

**Comment by HeroesandvillainsOS** [comment] 2017-01-24 16:06
@Tupolov so are we thinking there's a mod conflict with Burnes here? Is this something I should just remove or is it possible there's just an issue with ALiVE going on ATM?

**Comment by tupolov** [comment] 2017-01-24 16:21
I think the foxhound is ok, just need Highhead to check Logistics is processing data ok.

Something is causing corruption of your save, its not clear from the logs what that is. You could turn on data debug and provide the server RPT to help.

**Comment by HeroesandvillainsOS** [comment] 2017-01-24 16:27
Will do! I'll try to get it to you guys in the PM.

So far, I can only duplicate this with Real Weather being used. It seems to be the one thing that makes my loading fail in limited testing.

I'll flip it back on and get data debugged so hopefully the rpt will reveal something. I'm assuming you need the data debugged and not player data, so that the one I'll debug unless you reply back.

**Comment by tupolov** [comment] 2017-01-24 16:31
Turn on Debug for Weather too please

**Comment by HeroesandvillainsOS** [comment] 2017-01-24 16:59
You got it. :)

**Comment by highhead** [comment] 2017-01-24 17:02
Yeah, please CBA and ALiVE only repro mission with steps (sorry, but i have really limited time atm)! Quite sure I can solve it then!

**Comment by highhead** [comment] 2017-01-24 17:04
PS: I see that Tup committed a change that prevents sys data from locking up the loading screen with corrupt data, So it will improve either way, even if corrupt data is loaded!

**Comment by tupolov** [comment] 2017-01-24 17:13
BTW did you add LOP Civs to logistics as a whitelist class? They should not be stored as containers :D

**Comment by HeroesandvillainsOS** [comment] 2017-01-24 18:10
@Tupolov I did no such thing. I simply have LOP_TAK_Civ as the faction name in civ placement for civ spawns and civ vehicles, and have their individual classnames in Spyder Addons Ambience module for ambient traffic.

Perhaps there's an issue you can clarify that I can forward to Keeway? The more details on that the better.

**Comment by HeroesandvillainsOS** [comment] 2017-01-24 18:11
@Highhead, I'll see if I can repro with vanilla and get you the rpts. If it doesn't fail in a similar way to my modded mission, I'll get the debug rpt info to you for that instead.

**Comment by HeroesandvillainsOS** [comment] 2017-01-24 18:14
Tupolov, here is a mission that fails when Real Weather is used, in the event you are bored and have the required mods: https://forums.bistudio.com/topic/192272-alive-spcoop-1-8-inshallah-insurgency/

Though note I switched it to Arid for the time being. No worries on that though if you don't care to take a poke around. I'll try to get a vanilla test done in the PM.

**Comment by tupolov** [comment] 2017-01-24 19:42
Just need debug logs please :)

**Comment by HeroesandvillainsOS** [comment] 2017-01-25 00:09
On my way to try to repro with ALiVE CBA only, but in the meantime, here are the server rpt and plugin log when trying to load a save for the modded mission with the Weather module and Data module debugged:

https://www.dropbox.com/s/q57kie1uu907dg3/Persistence_Fail2_aliveplugin_2017-01-24_18-59.txt?dl=0
https://www.dropbox.com/s/llxea023zoidive/Persistence_Fail2_arma3server_2017-01-24_18-57-47.rpt?dl=0

**Comment by HeroesandvillainsOS** [comment] 2017-01-25 00:32
Ugh. And a quick vanilla mission is loading persistent data just fine with Real Weather. :(

**Comment by tupolov** [comment] 2017-01-25 00:49
Believe this could be the old roadblocks bug...  http://alivemod.com/forum/2588-stuck-on-loading-screen/0

Could this mission be that old?

**Comment by HeroesandvillainsOS** [comment] 2017-01-25 00:59
Yep! I started making this mission a long time ago, WAY before that thread, and have been constantly updating it as the platform and mod updates and as I learn new things. 

I see your posted workaround is to disable composition saving in the database module and start the mission with a new PBO name. Do you still want people to do this or have you fixed it internally, only for it to reappear? 

I wonder why Real Weather is coaxing the bug out?

Anyway, if you get a chance and could clarify what you want me to do and what the plan is (or isn't) regarding the bug, that would be helpful. I guess I'm having a hard time figuring out whether having composition and roadblock saving together is just a mission making no no and am intended result, or if this is a bug and not an ideal outcome.

And thanks for the help on all this by the way.

**Comment by tupolov** [comment] 2017-01-25 11:34
Only thing we can do for this mission is clean up the affected data and turn off persistent roadblocks in Mil Obj (Civ) (not compositions). Ultimately though the saved mission is no longer compatible with ALiVE. I've cleaned up the affending OPCOM roadblock objective, but nothing is stopping the mission from creating and saving more roadblocks. The "bug" is fixed in current release, but the issue is your data is no longer compatible with ALiVE when running persistent roadblocks and compositions.

I don't believe weather had anything to do with it, looks like weather inits fine, so not sure how that could affect your mission loading. Weather takes a few extra seconds to grab the weather data from the internet, so it might make loading longer, but shouldn't make it fail.

**Comment by HeroesandvillainsOS** [comment] 2017-01-25 16:05
@Tupolov I don't care if I need to start my mission over. What I'm confused and concerned about is that you seem to be saying my mission in general is somehow incompatible with the current version of ALiVE. Is that correct?

What can I do to make it current? And after doing whatever that is, that means I can save compositions in the data module and spawn roadblocks in the civ obj module safely?

AuTigerGrad has missions dating back to 2014 hat still get updates and work fine. What am I doing wrong?

**Comment by tupolov** [comment] 2017-01-25 16:07
I said your mission data is incompatible not your mission. If you start the mission with a new name, everything should work fine.

**Comment by HeroesandvillainsOS** [comment] 2017-01-25 16:09
Ah I see. And I can use civ obj roadblocks, assym roadblocks and persistent compositions?

**Comment by tupolov** [comment] 2017-01-25 16:09
yes

**Comment by HeroesandvillainsOS** [comment] 2017-01-25 16:11
Thanks for all the help guys. I really appreciate it. You always go above and beyond. :) Steam support can eat it!

**Comment by tupolov** [comment] 2017-01-25 16:12
Thanks for helping us get through these bugs!

**Comment by HeroesandvillainsOS** [comment] 2017-01-25 17:30
No problem! Hey, quick question. Did I start this mission before an ALiVE update, and then try to continue it after an ALiVE update?

I want to say no (I feel like I first saved the mission just a couple days ago lol) I didn't but that would be the only explanation that makes sense.

**Comment by tupolov** [comment] 2017-01-25 19:38
Thats not the issue.

You have data that was saved prior to 1.2.2. Mainly this is the data dictionary and OPCOM Objectives saved with a format no longer supported.

**Comment by coachwn** [comment] 2017-01-25 19:42
Good thread here...I think we might have similar issues on our mission as well.

**Comment by tupolov** [comment] 2017-01-25 19:51
http://alivemod.com/forum/2588-stuck-on-loading-screen

**Comment by HeroesandvillainsOS** [comment] 2017-01-25 21:00
@Tupolov I don't see how that's possible. 1.2.3 released the first week of December. I started this mission fresh with a new PBO 4 days ago. Check my player stats on War Room.

Operation Prophet from 4 days ago.

This is why I'm asking if my mission itself is somehow corrupted. Bad data module maybe? I don't see how it can contain data from before 1.2.2. This was a new operation.

**Comment by HeroesandvillainsOS** [comment] 2017-01-25 21:32
Gonna name the next one Spyderblacks_magical_mystery_slaughter.reshmaan.pbo because I'm fairly certain I haven't used that moniker yet. :)

**Comment by tupolov** [comment] 2017-01-25 23:20
Lol I'll take another look at some point this week :)

**Comment by HeroesandvillainsOS** [comment] 2017-01-26 04:35
Thanks @Tupolov. I just used a for certain brand new PBO name (to a different op) and it's the same result. It won't load persistent data.

Not sure if it's a corrupted mission, backwards compatibility issue with missions started with older versions, or if this bug with compositions/roadblocks is back or what.

**Comment by tupolov** [comment] 2017-01-26 09:19
Mission name? 
PBO name?

The bug with roadblocks and compositions should be fixed. 

Can you do same but with vanilla? Are you seeing the same issue?

**Comment by HeroesandvillainsOS** [comment] 2017-01-26 15:42
Mission name: Inshallah
PBO name: Taliban_OPS_Takistan.Takistan.pbo

I can certainly try vanilla. What do I need to see spawn first before I save? An Assymetric roadblock? What items exactly are corrupting?

**Comment by tupolov** [comment] 2017-01-26 16:13
Any composition and a roadblock.

**Comment by HeroesandvillainsOS** [comment] 2017-01-26 16:31
Composition, such as a random camp? I know you're busy so if you don't reply, I'll take that as a yes.

I'll give it a go in the PM. Hopefully it fails and we can expose whatever it is. I'd have to imagine at this point if it was as simple as a basic vanilla Assymetric mission corrupting save data, I certainly wouldn't be the first to report this. I have to wonder if it's simply a mod issue (though I don't really use that many, or I guess at least I don't use unpopular ones) or a corrupt module in my missions themselves.

We'll see. Thanks for all the help and quick replies.

**Comment by tupolov** [comment] 2017-01-26 18:02
Your original mission is definitely using old data. Your roadblocks are being saved as "roadblocks_n" where as since 1.2.3 roadblocks are saved as "comp_roadblocks_n".

Can you save your Inshallah mission after visiting an OPCOM roadblock?

**Comment by HeroesandvillainsOS** [comment] 2017-01-26 18:36
Sorry, you want me to physically visit a roadblock and try to save and then load, and then post the server rpt and plugin log? I'm not clear on your question.

Let's look at it from this angle. Let's try to clean up the old data. I mean, obviously if you guys could do your dev magic and clean up the backwards compatibility to accept the old classname, that would be sweet (and something to consider for updates in the future!). But I don't mind updating my mission(s) myself.

What module(s) should I delete and replace to give me the best chance at properly updating my missions to current ALiVE standards. Please don't say all of them or I will have a stroke! :)

**Comment by HeroesandvillainsOS** [comment] 2017-01-26 18:44
And I should note, I'm willing to do this and test with corrupt data for as long as it takes, in the event you want to fix this on your end incase other users have this problem. Updating my missions themselves by deleting/replacing things is only something I'm suggesting if you guys just want to be done with this and move on to other tickets. But I'm up for either option. Testing doesn't bother me.

**Comment by HeroesandvillainsOS** [comment] 2017-01-26 19:03
Ah! Sorry for the spam. I think I get you now. Saving the mission in the editor after seeing a roadblock *might* update my mission data. :) Yeah that makes sense. I can try that. :) Was that what you meant?

**Comment by tupolov** [comment] 2017-01-27 00:24
yes visit an OPCOM roadblock so it is spawned and save your Inshallah mission. 

The original mission in this ticket has data from pre 1.2.3 release, what we want to make sure is that the ALiVE version you are running no longer saves roadblocks incorrectly. If it does, this suggest you have an old version of ALiVE running (or an old PBO).

At this point its unlikely we are going to clean up data, just start the mission a fresh with a new mission name (and the latest version of ALiVE) and it should work! 

We want to eliminate the roadblocks issue first, but there are a couple of bugs that could be causing stuck loading screen in your original mission.

**Comment by coachwn** [comment] 2017-01-27 00:52
@HeroesandvillainsOS It may be caused as a result of a copy and paste of ALiVE instead a complete removal before you updated as well. I have had it happen when I didn't delete all instances of ALiVE when working on missions. It loads and operates somewhat correctly locally until you get into server based testing.

**Comment by HeroesandvillainsOS** [comment] 2017-01-27 04:49
Oh sweet! Progress! @Tupolov that worked! FWIW, I use the Workshop version of ALiVE so I'm certainly up-to-date and I regularly get aliveserver from the main site as well.

I do have a suspicion that there may be some other wonky backwards compatibility issues going on here as well so I'll post the server rpt and plugin log for this session just incase it's of interest:

https://www.dropbox.com/s/0ot0ahbwyij0hsg/Persistence_FTW_aliveplugin_2017-01-26_23-28.txt?dl=0
https://www.dropbox.com/s/oceueanmj5gzkl3/Persistence_FTW_Arma3_2017-01-26_23-24-47.rpt?dl=0

If you want to check the mission data, I named this one Taliban_OPS_Takistan1.Takistan.pbo, mission name Inshallah.

Let me know what you're thinking, Tupolov. In the editor, I waited 25 minutes for the first roadblock to spawn. I then teleported to it, exited back to the editor and saved. I then loaded the mission on the server, waited another 25 minutes for any roadblock to spawn, and then teleported to that and server saved and exited. And as I said, trying to continue the mission works! :)

Would any other compositions or objects need similar treatment in the editor to fully update this mission on my end? Such as different style roadblocks storing under different names, or perhaps random camps or anything else that can spawn that might be out of date?

**Comment by HeroesandvillainsOS** [comment] 2017-01-27 05:13
I guess while I'm at it, what about roadblocks spawned by the civ obj module? Do you think this data corruption would apply to those as well? I have a few non-Assymetric missions I made awhile ago in the editor that I spawn regular old civ roadblocks in too. Should I go through my Invasion/Occupation missions in a similar fashion, or did this bug only apply to roadblocks spawn by Assymetric commanders?

**Comment by tupolov** [comment] 2017-01-27 08:58
Yes civ placement roadblocks too please.

**Comment by tupolov** [comment] 2017-01-27 08:59
The RPT should report spawning roadblock compositions, it will give you the position.

**Comment by HeroesandvillainsOS** [comment] 2017-01-27 15:40
What would I be ctrl+f'ing? I've never tried to follow a live rpt before. 

I'm thinking it may be easier to just set them to extreme (I usually set them to low), and teleport to a few occupied junctures, which I'd assume would have a good chance of spawning one, and save. Then revert the mission(s) back to low. 

Anyway, hopefully that does the trick. I've got about 8 missions I need to go through. Maybe more lol. So it may be a bit before I get a chance to thoroughly test persistent saving and loading on a server. Thanks for all the help, Tupolov.

**Comment by tupolov** [comment] 2017-01-27 17:25
COMPOSITION

**Comment by HeroesandvillainsOS** [comment] 2017-01-27 19:53
Thanks. So I can hopefully get this done in one swoop, can I just spawn one roadblock or so I need to spawn at least one for all sides? Not sure if they're considered shared assets for this purpose or not.

**Comment by HeroesandvillainsOS** [comment] 2017-01-28 18:17
Ok, so I went ahead and set roadblocks in the civ obj module to extreme (for the enemy side only!) and teleported to them so they materialized and then backed out to the editor and saved.

So I've now done this with enemy Assymetric and enemy civ obj roadblock. Hopefully we're all good now.

I'll report back in a couple days after I get a few persistent sessions going. If what I did is likely not enough to make my missions "current," for any composition or module for that matter (these missions were all started a long time ago), please let me know.

**Comment by tupolov** [comment] 2017-01-28 18:31
Backed out to the editor?

Test should be:

1. Set persistent compositions in data module
2. Set roadblocks in Mil Placement (Civ)
3. Set asymmetric on opcom and debug
4. Save as MP mission 
5. Run mission on dedicated
6. Connect to mission, teleport to a roadblock
7. Make sure there is a roadblock objective for OPCOM
8. Save Server and Exit back to lobby.
9. Run mission again on dedi
10. Connect and make sure mission loaded correctly.

Remember Hosted MP is not supported with persistence.

BTW you should really setup the Dev env so you can test very latest code. Then we can fix and test in real time given how much you test. :)

**Comment by HeroesandvillainsOS** [comment] 2017-01-28 20:23
Sorry I wasn't clear. Aside from using the dev release of ALiVE, I've run the test exactly as you listed it, except for the save as MP mission part.

1. Loaded mission in SP editor 
2. Set persistent roadblocks and camps to on
3. Turned on civ obj roadblocks (to extreme so I could find one easily)
4. Debugged Assymetric OPCOM with roadblocks set to yes 
5. Pressed play on the mission in the SP editor 
6. Teleported to a civ obj roadblock 
7. Teleported to an Assymetric roadblock
8. Exited back to the editor and saved as a SP mission

I then take the SP mission PBO, place it in my MP missions folder, and direct my dedicated server to the MP Mission PBO. I haven't had a chance to test persistence yet. But in theory, were these steps acceptable to update my missions to the current ALiVE standards? I ran an earlier test on a dedicated server after having done this with Assymetric roadblocks only with Inshallah and loading the persistent save worked. Last night I went in and did this again but for civ roadblocks too.

Does that sound ok?

**Comment by HeroesandvillainsOS** [comment] 2017-01-28 20:28
When I say "test" that is a bad word. What I'm trying to do is update my missions themselves to the new class of roadblocks.

Your test is viable for testing persistence purposes, but my missions themselves were loading persistent data at all until I did the steps I listed above. I think that's because my missions had "stored" for lack of a better word the old roadblock class. My steps were designed to spawn the new class and then save the mission PBO to hopefully get the new class in my mission.sqm

**Comment by HeroesandvillainsOS** [comment] 2017-01-29 05:34
Oh damn. The persistent data is still corrupted. :( I'm out of ideas.

So in full, here are the steps I took. And note I am using the current Workshop version of ALiVE for editing and playing. It's the only version I ever use.

1. Load mission in the SP editor 
2. Make sure Persistent camps/roadblocks are set to yes
3. Placed civ obj roadblocks are set to extreme
4. Set OPCOM Assymetric roadblocks are set to yes
5. Pressed play in the editor and teleported to a civ obj roadblock and Assymetric roadblock
6. Saved the mission in the SP editor
7. Placed the mission PBO in my MP missions
8. Launched dedicated server with this PBO
9. On the dedicated server, I teleported to several civ obj roadblocks and several Assymetric roadblocks
10. Server save and exit
11. Exited the game and closed the server.
12. Enter the game and start the server again
13. Tried to play the same mission and persistent data doesn't load (it stays stuck on the loading screen).

Mission name Inshallah. PBO name Roadblock_Test_Takistan.Takistan.pbo

**Comment by tupolov** [comment] 2017-01-29 09:02
You don't need to test in SP, that has zero effect on how we save data.

Now you have tested correctly in MP we need the logs. Thanks.

**Comment by tupolov** [comment] 2017-01-29 10:26
Ok, so checked the database and the version of ALiVE you are using is still saving persistent roadblocks as "roadblocks_n" instead of "comps_roadblocks_n".  

So i've just downloaded our latest release and it appears that certain data commits are not in it... This is bad. This basically means that our current release doesn't have our latest code. We will rectify asap.

**Comment by tupolov** [comment] 2017-01-29 14:48
Try this new build with a new mission thanks https://github.com/ALiVEOS/ALiVE.OS/releases/tag/v1.2.9.1701291

**Comment by HeroesandvillainsOS** [comment] 2017-01-29 16:29
Thanks! A new PBO name or literally a new mission made from scratch? My top priority is making sure my current missions persist data. I'm planning Workshop releases for about 7 of them very soon.

**Comment by highhead** [comment] 2017-01-29 18:07
do it like this and you should be fine with the build linked above (thats important, will hit da streets soonTM):

- open your Inshallah mission in EDEN
- open every ALiVE module and close it (you may ofc want to see if there are new settings added to the modules that you want to use).
- save your mission to a new name

**Comment by HeroesandvillainsOS** [comment] 2017-01-29 18:22
As always, the help and guidance is appreciated @tupolov and @highhead. I'll report back later on. 

Tupolov, I kind of agree with you at this point it would make sense for me to set up the dev environment considering how much I tinker around. It's every day at this point, for the most part. If you have a link at some point (no hurry) for how to set that up (assuming there's special instructions), that would be excellent.

**Comment by HeroesandvillainsOS** [comment] 2017-01-30 05:23
Sweet, we're making progress. I was able to successfully load a persistent mission with today's update. Although a new mission PBO name was able to save and load data, the roadblocks themselves however are not persisting even though the option is set to yes. When I load back into the server, the enemies occupying the roadblocks are still there (where they should be), and the vehicles manning the roadblocks too, but the actual compositions themselves do not spawn upon loading.

Mission name Inshallah
PBO name Roadblock_Test_Takistan1.Takistan.pbo
plugin: https://www.dropbox.com/s/7s6xk0498hoerpr/Persistence_Roadblock_aliveplugin_2017-01-29_23-52.txt?dl=0
server rpt: https://www.dropbox.com/s/tf31mi9ccbe7uk0/Persistence_Roadblock_arma3server_2017-01-29_23-51-01.rpt?dl=0

**Comment by tupolov** [comment] 2017-01-30 06:24
Hey man, thanks again for testing. Looks like with this test the data saved exceeded Arma's data limit, not your problem, but something we need to address.

**Comment by HeroesandvillainsOS** [comment] 2017-01-30 06:36
Oh lol. No big deal. For testing purposes I ramp up the OPFOR spawns way higher than when I actually play the mission for real. I'd assume that would bring the data total down. But so far so goo! If I'm able to load data I'm a happy player!

Thanks for everything Tupolov and Highead! Give me a day or two to confirm persistent data continues to load and I'll close the ticket. I appreciate it guys.

**Comment by highhead** [comment] 2017-02-28 18:03
Hey comrade! I am closing this one, feel free to reopen if it still errors out the same way as before!

**Closed by highhead** 2017-02-28 18:03 UTC
Labels: bug

**Comment by HeroesandvillainsOS** [comment] 2017-02-28 18:32
No problem. I've been too busy to put any real testing into persistent data.
