### ISSUE TITLE
Persistent Markers not showing up after player exiting

### ISSUE THREAD

**Issue by AUTigerGrad** [ALiVEOS/ALiVE.OS#168] opened 2016-11-15 16:08 UTC
I'm logged in as the server admin.

When I first do a server save and exit, then refresh the server and reload the mission...the markers appear and I can see everything.

However, when I player exit from my session..then return later and load in...the markers are no longer visible.  Sometimes...if I player exit out and come back in..they will appear but it is not consistent.  The only times I can see the markers is after loading the mission from a server save and exit.

**Comment by marceldev89** [comment] 2016-11-15 16:33
Possibly related to and/or duplicate of https://github.com/ALiVEOS/ALiVE.OS/issues/95?

**Closed** 2016-11-15 16:53 UTC
