### ISSUE TITLE
Infinite Loading Screen (Custom Objective Module)

### ISSUE THREAD

**Issue by 123B3n** [ALiVEOS/ALiVE.OS#471] opened 2017-11-24 22:11 UTC
### Prerequisites

* [X] Can you reproduce the problem using ALiVE and CBA Only?
* [X] Are you running the latest version of ALiVE? (ALiVE_1.4.0.1709191)
* [X] Are you running the latest version of CBA_A3? (CBA_A3 v3.4.1.170912)
* [X] Have you attached an unbinarized SQM?
* [X] Have you attached your RPT (If the issue relates to data, also attach Server RPT and ALiVE Plugin Log)?
**Not getting any ALiVE Plugin Logs for some reason, I did earlier today...**
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description
My server has been working flawlessly to the point when I stopped it a couple of months ago, just relaunched it and I end up with an infinite loading screen, been spending 8 hours right now trying to figure out what the issue is, but I've pretty much narrowed it down to one module which would be the Custom Objective Module. I've tested the default parameters, I've changed the parameters to my own I've pretty much tested everything, no matter what I do as long as the module is on the mission file it ends up with an infinite loading screen.

### Steps to Reproduce
1. Setup the core ALiVE modules
2. Add Civilian modules,
3. Add Military AI Commander
4. Add the Custom Objective Module
5. Sync the Custom Objective Module <=> Military AI Commander
6. Enjoy the endless loading screen.

**Expected behavior:** Mainly be able to enter the mission itself, be able to see my character and walk around.

**Actual behavior:** Infinite loading screen

**Mission File:** [alive-test.Tanoa.zip](https://everest-community.net/alive/alive-test.Tanoa.zip)
**Server RPT:** [arma3server_x64_2017-11-24_22-49-55.rpt](https://everest-community.net/alive/arma3server_x64_2017-11-24_22-49-55.rpt)
**Client RPT:** [Arma3_x64_2017-11-24_22-46-28.rpt](https://everest-community.net/alive/Arma3_x64_2017-11-24_22-46-28.rpt)

**Comment by 123B3n** [comment] 2017-11-24 23:09
Issue is the composition, leaving it blank gets the module to work again. 
Thanks to [HeroesandvillainsOS](http://alivemod.com/forum/member/1611-heroesandvillainsos) who figured it out.

Could kinda say the bug is resolved, however, it's still a bug and this is only a temporary fix I'd guess.

**Comment by Whigital** [comment] 2017-11-24 23:55
The problem is indeed the composition (`mediumMGCamp3`) which does not exist, and the custom placement module isn't handling that exception.

**Comment by highhead** [comment] 2017-12-03 16:09
I pulled the fix to master! Will be in upcoming release (which is soon(tm))

**Closed by highhead** 2017-12-03 16:09 UTC
Labels: Needs Repro
