### ISSUE TITLE
curl_easy_perform() failed

### ISSUE THREAD

**Issue by Kicillof** [ALiVEOS/ALiVE.OS#545] opened 2018-09-17 15:30 UTC
### Prerequisites

* [x] Can you reproduce the problem using ALiVE and CBA Only?
* [x] Are you running the latest version of ALiVE ?
* [x] Are you running the latest version of CBA_A3?
* [x] Have you attached an unbinarized SQM?
* [x] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [x] Have you attached screenshots of the Parameters set on the offending Module?

### Description

I'm having trouble with saving the persistence since a month. When I press Server Save and Exit button, it doesn't show the Alive Tablet, it just takes me back to the lobby without saving the persistence.

I've already re-edited the mission, replaced all Alive modules, replaced the alive.cfg file, reconfigured the server in the War Room, updated NET Framework and reuploaded Alive and AliveServer, but the problem is still there.

You can find the error in this fragment of the Alive Plugin log:

> [2018-09-17 05:23:47] [info]     Checking WarRoom access...
> [2018-09-17 05:23:47] [info]     URL: http://alivemod.com/api/authorise?group=USML&localDB=false
> [2018-09-17 05:23:47] [info]         WarRoom access granted.
> [2018-09-17 05:23:47] [info]     Checking DB access...
> [2018-09-17 05:24:08] [error] ###### curlGet ######
> [2018-09-17 05:24:08] [error]     Error: curl_easy_perform() failed
> [2018-09-17 05:24:08] [error]     RAW:   Couldn't connect to server
> [2018-09-17 05:24:08] [error] ###### HandleMessage - StartALiVE ######
> [2018-09-17 05:24:08] [error]     Error: curlGet() failed
> [2018-09-17 05:24:08] [error]     RAW:   ['curlGet','ERROR','curl_easy_perform() failed']
> [2018-09-17 05:24:08] [debug]     Return value [['StartALiVE','ERROR','['curlGet','ERROR','curl_easy_perform() failed']']]

And also, you can find this on the server.rpt:

>  5:24:08 ALiVE Extension (ALiVEPlugIn) Error: ['StartALiVE','ERROR','['curlGet','ERROR','curl_easy_perform() failed']'] CMD: StartALiVE ['true']
>  5:24:08 ALIVE_SYS_DATA START PLUGIN: SYS_DATA_ERROR
>  5:24:09 DATA: Attempting to load ALiVE web services config.
>  5:24:30 Warning: 21216 ms spent in callExtension calling name: "ALiVEPlugIn", function: "SendJSON ['GET','sys_data/config','']"
>  5:24:30 ALiVE Extension (ALiVEPlugIn) Error: ['SendJSON','ERROR','['curlGet','ERROR','curl_easy_perform() failed']'] CMD: SendJSON ['GET','sys_data/config','']
>  5:24:30 ALiVE-0 CANNOT CONNECT TO CLOUD SERVICE, DISABLING WEB SERVICES
>  5:24:30 ALiVE-0 EXITING DATA INIT AS CANNOT CONNECT TO COUCHDB
>  5:24:30 DATA: Waiting for global DISABLED variable...
>  5:24:30 DATA: SYS DATA enabled: false

Either way, back in 2016 a guy reported the same problem that I have and it was told that the Alive War Room database ran out of space. You can check this out here on the Alive Forum: [http://alivemod.com/forum/1661-war-room-stopped-working/0](http://alivemod.com/forum/1661-war-room-stopped-working/0)

The weird thing is that persistence works for me when I host the server on my computer, but not on the server that I'm renting, even though Alive Persistence worked flawlessly on that same server during months.

I'm attaching here:

- a mission with Alive and CBA only that has the exact same issue: [mission.txt](https://github.com/ALiVEOS/ALiVE.OS/files/2389146/mission.txt)
- my .rpt: [Arma3_x64_2018-09-17_00-37-42.txt](https://github.com/ALiVEOS/ALiVE.OS/files/2389173/Arma3_x64_2018-09-17_00-37-42.txt)
- server .rpt: [arma3server_2018-09-17_05-18-04.txt](https://github.com/ALiVEOS/ALiVE.OS/files/2389162/arma3server_2018-09-17_05-18-04.txt)
- AliveServer log: [aliveplugin_2018-09-17_05-23.txt](https://github.com/ALiVEOS/ALiVE.OS/files/2389165/aliveplugin_2018-09-17_05-23.txt)

### Steps to Reproduce

1. Execute a mission with Alive Persistence
2. Try to save the server

**Expected behavior:** [Save persistence]

**Actual behavior:** [Doesn't save persistence]

**Comment by secit** [comment] 2018-09-20 07:32
It looks like a normal timeout while contacting the Alive server.
My best guess would be that your provider is blocking some traffic.
Make sure outgoing TCP port 5984 is open.

If you have access to a browser on the server then try to open http://db.alivemod.com:5984 as a quick test.

**Comment by secit** [comment] 2018-09-20 07:36
Duplicate of #531

**Comment by Will-Nichols** [comment] 2018-12-11 19:14
Having the same issue as @Kicillof 

Our dedicated server is not persisting information when I use the server save and exit functions from the admin menu. It will automatically kick over into a server restart mode and drop the admin back into the lobby and mission resets from the beginning.

I can confirm that the mission is being seen by the ALiVE DB as it is showing my stats on the War Room currently. Here is our group link for the [War Room](http://alivemod.com/war-room/showorbat/4575).

**Comment by Will-Nichols** [comment] 2018-12-12 16:02
@marceldev89 can you take a look at this and see what might be the problem? 

Here is the RPT for our dedicated server and I can confirm via a CBA, ACE, ALiVE repro last week that it does not persist as well when that mission is running.

**Comment by marceldev89** [comment] 2018-12-13 10:45
The `curl_easy_perform()` errors are caused by a connection problem between your server and our server. Contact your host support and/or our host support ([ArmaHosts](https://armahosts.com/)) to figure out what's wrong. A few weeks ago it turned out that armahosts was blocking all connections from ovh.

**Comment by Will-Nichols** [comment] 2018-12-13 13:14
@marceldev89 I think you can close this one as it seems like I have figured out the biggest culprit on our end.

**Closed** 2019-04-15 20:31 UTC
Labels: Persistence
