### ISSUE TITLE
Player Resupply slingloading issues

### ISSUE THREAD

**Issue by marceldev89** [ALiVEOS/ALiVE.OS#107] opened 2016-10-03 13:41 UTC
1. Ghost Hawk cannot (anymore) slingload the default supplies container `ALIVE_B_supplyCrate_F` because it's mass (5000) is higher than the Ghost Hawk's `slingLoadMaxCargoMass` value (4000). The mass of the contianer seems excessive and could be adjust with the `setMass` command if there's nothing else at play. (CH-67 Huron should be able to slingload the container)
2. Slingloading vehicles fails if _someone_ is within the spawn range set in the Virtual AI System module, possibly because the vehicle spawns with a parachute attached.
3. Sometimes the transport vehicle will not release the slingloaded vehicle and keep hovering until killed.
4. Combat Logistics should probably select the transport vehicle actually capable of slingloading the objects (in the case of vehicles).
5. Transport vehicles that failed to slingload stuff still fly to their destination and do their thing but without the supplies.
6. Perhaps the list of vehicles in the Player Resupply dialog should be filtered to what's actually possible.
7. Some script error popping up that's seemingly related to this:

```
15:21:45 Error in expression <[ALIVE_profileHandler, "getProfile", _x select 1] call ALIVE_fnc_profileHandler;>
15:21:45   Error position: <select 1] call ALIVE_fnc_profileHandler;>
15:21:45   Error Zero divisor
15:21:45 File x\alive\addons\mil_logistics\fnc_ML.sqf, line 6449
```

**Comment by tupolov** [comment] 2016-10-25 12:36
1. BIS seemed to have set the mass of resupply boxes to 5000 :( Seems like a bug on their end. Will override via our calculation...
2. This was an original design decision in that vehicles shouldn't "just spawn", so if they players are near by then the vehicle is just parachuted in. I guess the issue is if players are nearby but the resupply request came from a different area.
3. Will take a look
4. Not sure what this means?
5. Will take a look
6. It currently is I believe.
7. Will take a look.

**Comment by tupolov** [comment] 2016-10-26 22:51
1 is fixed with https://github.com/ALiVEOS/ALiVE.OS/commit/9906afec7dea4aabcdb5fa39c577b7661c3c57f0

**Comment by tupolov** [comment] 2016-10-31 22:23
Ok put in a bunch of fixes. New responses here

1. Fixed in dev
2. This is by design, if players are nearby and assets are being delivered by road, they are airdropped at the main "logistics" base. This is so vehicles don't magically appear on the road (they appear from above). If there is a heli insertion, the assets that are being delivered by heli are spawned at 500 ft above the base and slung under a helicopter.
3. Fixed in dev
4. It does this today. If you request or AI request a heli resupply, it will look for a suitable chopper to carry the assets. If a chopper cannot be found for any of the assets, it will revert to a standard convoy delivery for the entire request (so you don't get a mixed delivery). If selected it will find a chopper from just your faction (or faction and side).
5. Slinging should be more robust now, but accidents happen. The chopper involved will still escort the others to the location providing additional support. :)
6. As before, good idea, feature enhancement - add another ticket.
7. I believe this is fixed in dev.

Feel free to test!

**Comment by tupolov** [comment] 2016-11-07 21:40
Expired

**Closed by tupolov** 2016-11-07 21:40 UTC
Labels: bug, Needs Testing
