### ISSUE TITLE
EventHandlers error when exporting faction using RHS from ORBAT Creator

### ISSUE THREAD

**Issue by coachwn** [ALiVEOS/ALiVE.OS#331] opened 2017-04-20 06:11 UTC
Similar error to the one posted here; ORBAT Creator errors out when inheriting classes that do not contain Eventhandlers.CBA_Extended_EventHandlers_base #329 

Here is a pastebin of the autogen.hpp file. https://pastebin.com/26PZJ43u

I am using the latest version of ALiVE to export the faction. 

File 15th_pla\autogen.hpp, line 1331:
/CfgVehicles/O_15thPLA_J20_01.Eventhandlers: Undefined base
class 'EventHandlers'

Full faction available via Steam Workshop linked here: http://steamcommunity.com/sharedfiles/filedetails/?id=867968975

**Comment by marceldev89** [comment] 2017-04-20 12:05
This is a duplicate of #329, please continue there. :smiley:

**Closed by marceldev89** 2017-04-20 12:05 UTC
