### ISSUE TITLE
ALiVE spawning air units at map origin

### ISSUE THREAD

**Issue by aritsune** [ALiVEOS/ALiVE.OS#289] opened 2017-02-18 09:52 UTC
I've set up a fairly simple ALiVE mission in Takistan with a custom faction made in ORBATRON. It works mostly fine but I've noticed the system keeps trying to spawn air units at [0,0,0] where they instantly clip into each other and explode. Have I set something up incorrectly or is this a bug?

**Comment by HeroesandvillainsOS** [comment] 2017-02-18 16:17
There have been a couple of similar reports like this by Vegas, and I'm *pretty sure* there was an outside mod causing the problem.

Can you first see if this happens with a vanilla faction (ALiVE, CBA and CUP Terrains only), then if it doesn't, just add in your ORBAT faction and whatever it requires and see if it happens then?

You'll want to remove as many possible causes for this as possible to narrow down the culprit.

@Vegas what ended up being the cause for you?

**Comment by SpyderBlack723** [comment] 2017-02-18 17:41
What map are you using?

**Comment by HeroesandvillainsOS** [comment] 2017-02-18 18:33
He says Takistan in the post which is the same as Vegas when he reported it. Strange.

**Comment by SpyderBlack723** [comment] 2017-02-18 18:33
Check if there is an objective at that location.

**Comment by HeroesandvillainsOS** [comment] 2017-02-18 18:36
Or yellow arrows

**Comment by Vegas** [comment] 2017-02-23 02:30
@HeroesandvillainsOS I never found a solution for my specific issue. The "yellow arrows" appear to show up on certain maps, possibly as this user says the "map origin".

In my case, there was no way to fix this. Blacklisting these areas had no effect. 

I know for a fact that these strange areas are being used as the origin for many units, and if you place more than one respawn_west marker and allow players to select where they want to spawn, until they select one they are actually held over these markers. A similar issue happens for Headless Clients as they are locked to these locations as well.... very odd..

**Comment by HeroesandvillainsOS** [comment] 2017-02-23 19:54
So why did you close the ticket? Do you determine it was something non-ALiVE related (meaning, you saw evidence of something unusual going on even when ALiVE isn't loaded)?

Can you post a simple repro mission please (ALiVE, CBA and the map mods only)?

**Comment by aritsune** [comment] 2017-02-26 21:48
Sorry for the delay, I've been a little busy. I've just tested the mission with only the following mods:
CBA_A3
CUP Terrains Core
CUP Terrains Maps
ALiVE

The issue still occurs, several helicopters spawn near [0,0,0], clip into each other and explode.

I've since ported the old mission to a different map (Lingor) and it works fine, helicopter units end up in the battlefield as they should. The bug might be related to [0,0,0] being open sea in most terrains and ALiVe working under this assumption, as it isn't in Takistan.

Here's the reproduction mission with minimal mods:

[alive_takistan_repro.Takistan.zip](https://github.com/ALiVEOS/ALiVE.OS/files/802316/alive_takistan_repro.Takistan.zip)

**Comment by SpyderBlack723** [comment] 2017-02-27 02:01
Try reproducing with Altis or Stratis. If it only occurs on mod maps it's likely needing a reindex.

**Comment by aritsune** [comment] 2017-02-27 06:57
Just tested it on Stratis and yeah, it doesn't happen. Takistan at least definitely needs reindexing.

**Comment by HeroesandvillainsOS** [comment] 2017-02-27 16:27
I've already committed to reindexing CUP maps that have become screwed up due to the recent JBAD integration. I certainly don't mind, but I'm going to make a plea with the devs here.

Can any of you guys determine with certainty this issue is being caused by bad indexing and can only be fixed by reindexing? Let's assume for a second 10 or so maps from CUP need to be reindexed. This will take me around 20 hours (give or take). And not only that, but I have gone through Takistan (and Zargabad, and Reshmaan) with a fine-tooth comb, looking at every single building, and the indexes look absolutely perfect to me. Perfect. 

I feel like it would be a waste of a considerable amount of time if a dev can't at least (A) confirm the issue and (B) determine it can only be fixed by indexing. Especially considering they all look good on my end. But yes, if A and B are 100% true, I will reindex Takistan (and a bunch of others) for you guys.

**Comment by aritsune** [comment] 2017-02-27 17:14
I do suspect it might not be an indexing issue since that's seemingly the only place helicopter groups spawn. I think they're supposed to be reinforcement choppers?
I'll try removing the Logistics module and see if the issue persists.

**Comment by HeroesandvillainsOS** [comment] 2017-02-27 17:46
We have another report posted just now about support choppers flying to this position over on BIS forums. He didn't say which map or mods but it sounds like a relatively similar problem. I asked for clarification so we'll see. There's definitely something strange going on.

**Comment by highhead** [comment] 2017-02-27 18:40
the original report sounds more like MIL Logistics, and the guy on BIF says its happening with CS modules which is only creating the Air units once at the very beginning (unless killed and then respawned).

can it be replicated with CS? Would help to narrow down the cause, it definatly should NOT spawn at 0,0,0 at all but fail with grace (again) :)

**Comment by HeroesandvillainsOS** [comment] 2017-02-27 19:10
Yeah the guy on BIS seems to be talking about CS and them moving to 0,0,0 on RTB. All the other reports (here and from user Vegas), seem to be relating to ambient aircraft in the MIL Placement or LOGCOM. And for Vegas, physical infantry units. It's weird because I've never seen any of these things.

https://github.com/ALiVEOS/ALiVE.OS/issues/269
https://github.com/ALiVEOS/ALiVE.OS/issues/267

Which were closed without any solution, BTW.

So we have reports of ambient aircraft (MIL Placement), CS, and infantry spawning (either placement or MIL LOG). I'll take a peak later and see what's up and if I can repro with and without all these features.

**Comment by highhead** [comment] 2017-02-27 19:13
Seems like I can replicate it with CUP Terrains - Full 1.1.0, dunno if its outdated though.

**Comment by HeroesandvillainsOS** [comment] 2017-02-27 19:19
Yeah they're up to 1.3.0 now. Though who knows if that makes a difference. What it does say at least is it's not related to the new JBAD integration. So. That's....good I guess?

What are you seeing? Is it ambient Mil Placement air assets or what?

**Comment by HeroesandvillainsOS** [comment] 2017-02-27 19:38
It sounds to me like there's (probably hidden) objectives or invisible helipads at this location, which I think would account for all of the described behavior (units, Mil LOG, CS RTB). So it would make sense in one way that a reindex might help, but if there's nothing there to blacklist, I could see it reindexing a waste of time too and that the location would continue to be recognized.

This is weird.

**Comment by aritsune** [comment] 2017-02-27 19:47
They have to be from Mil Placement since my test mission only has commander+civ+mil placed down. The helicopters do have crew though, and in fact I've seen some show up under the list of commander groups with the C2ISTAR tablet as 'Air Group', so I -think- they're not ambient vehicles.

I should try a mission with nothing but a military placement module to make sure this isn't some bizarre interaction between modules.

**Comment by HeroesandvillainsOS** [comment] 2017-02-27 20:05
Sure thing man. Keep going. Narrowing things down can't hurt. :) When I say ambient, it's probably a bad word because I think they will always be manned. I don't use the Air Assets option myself (I manually place my own if needed to avoid the whole explody-explody on mission start thing) but I'm pretty sure they spawn in as air units with pilots that would certainly show up in the commander tablet.

**Comment by aritsune** [comment] 2017-02-27 20:06
Okay, made another test mission and I can reproduce the issue with only these modules:
- ALiVE (Required)
- Virtual AI System
- Military Placement

Additionally, I tried both setting a TAOR far away from 0,0,0 and a blacklist marker that covered it, and the issue still occurred. So it seems unlikely that this is happening because there's an objective at that position.

Here's the bare minimum reproduction mission:
[alive_repro2.Takistan.zip](https://github.com/ALiVEOS/ALiVE.OS/files/804876/alive_repro2.Takistan.zip)

**Comment by highhead** [comment] 2017-02-27 20:12
the issue is there are no helipads at all defined in the map, at least in my version.

nearestObject [player, "HeliH"] returns a null-object which defaults to position [0,0,0]. This is because either there is really no single helipad present on the map (maybe outdated version) or if there is the config parent "HeliH" is not set on the A2 / A1 helipads.

I am fixing this situation by not placing helicopters if there are no helipads present. You can then place invisible helipads manually to work around it easily.

**Comment by HeroesandvillainsOS** [comment] 2017-02-27 20:25
You're the man, Highhead! And Aritsune, thanks a lot for testing and all the trial and error stuff. Good job guys.

**Closed** 2017-02-27 21:27 UTC
