### ISSUE TITLE
Re-Index Malden 2035 (Civilian Placement - Only 1-2 Civilians spawning since Laws of War Update)

### ISSUE THREAD

**Issue by nobodyshome** [ALiVEOS/ALiVE.OS#421] opened 2017-09-09 12:36 UTC
### Prerequisites

* [Yes] Can you reproduce the problem using ALiVE and CBA Only?
* [Yes] Are you running the latest version of ALiVE ?
* [Yes] Are you running the latest version of CBA_A3?
* [No] Have you attached an unbinarized SQM?
* [No] Have you attached your RPT (If the issue relates to data, also attach Server RPT and ALiVE Plugin Log)?
* [No - Changing parameters doesn't affect it] Have you attached screenshots of the Parameters set on the offending Module?

### Description

[1-2 Civilians Spawn per Town, no matter what change you make module wise it will always be 1-2 Civs]

### Steps to Reproduce

1. [Place Down 3 Modules (Virtual AI, Civ Placement, Civ Population)]
2. [Spawn in and go into Zeus]
3. [Watch a town for 1-10 minutes, only 1-2 civilian will spawn]

**Expected behaviour:** [More than 1-2 Civilians spawning around and in a town]

**Actual behavior:** [At most 2 Civilians spawn, most of the time only a single one]

Apologies if I have filled any of this wrong, I can amend and give any more information if requested.

**Comment by highhead** [comment] 2017-09-09 12:37
Uh Oh!

Thanks for the report, will check right away!

**Comment by nobodyshome** [comment] 2017-09-09 12:45
![arma 3 screenshot 2017 09 09 - 13 43 40 26](https://user-images.githubusercontent.com/4974214/30240281-0134ae7e-9565-11e7-95d5-87be66323816.png)

Here is the only error that repeats multiple times when over a town in Zeus. Not sure if this helps.

**Comment by highhead** [comment] 2017-09-09 13:08
Hi!

1. You still have mods loaded according to your screenshot, thats not vanilla (only ALiVE & CBA loaded is).

2. You do not have ALiVE required placed. This module ensures that ALiVE is loaded correctly and in a timely fashion.

3. When set up correctly it loads up as intended. (mission [here](http://s000.tinyupload.com/download.php?file_id=95493749957178234469&t=9549374995717823446982077))

![arma3_x64 2017-09-09 14-56-08-07](https://user-images.githubusercontent.com/13004589/30240414-64452588-9570-11e7-9457-896a6768e767.jpg)

4. Please try to use this latest RC which is about to hit the streets: https://github.com/ALiVEOS/ALiVE.OS/releases/tag/v1.3.7.1709081

Feel free to re-open if its not resolved with the steps

**Comment by nobodyshome** [comment] 2017-09-09 13:12
![arma 3 screenshot 2017 09 09 - 14 10 46 80](https://user-images.githubusercontent.com/4974214/30240469-b706a1f0-9568-11e7-9ede-c309d27e5ef6.png)

I have ALiVE Required placed(Same one in the image right?), the same error occurred with just CBA and ALiVE, I just posted grabbed a picture of the error when the mods were loaded to save restarting my game.

**Comment by highhead** [comment] 2017-09-09 13:13
Can you please upload the vanilla mission so i can poke at it?

**Comment by highhead** [comment] 2017-09-09 13:13
and RPT would be helpful too

**Comment by highhead** [comment] 2017-09-09 13:14
PS: in the repro steps ALiVE required is missing :)

**Comment by nobodyshome** [comment] 2017-09-09 13:19
Repro?

**Comment by nobodyshome** [comment] 2017-09-09 13:20
[tempMissionMP.Malden.zip](https://github.com/ALiVEOS/ALiVE.OS/files/1289810/tempMissionMP.Malden.zip)

**Comment by highhead** [comment] 2017-09-09 13:21
Repro = Reproduction steps. ALiVE required was missing in there, thats why i pointed it out in the first place at all. Trying your mish.

**Comment by highhead** [comment] 2017-09-09 13:22
PS: Can you please try mine from above (its Stratis)

**Comment by nobodyshome** [comment] 2017-09-09 13:22
Ah, yeah that was an oversight on my part. I just presumed since it's required there was no point mentioning it.

**Comment by nobodyshome** [comment] 2017-09-09 13:23
Will try now, if it works it could be something due to Malden.

**Comment by nobodyshome** [comment] 2017-09-09 13:28
Okay, can confirm your mission works.
However, copying everything from your mission to a new one on Malden it no longer works.

**Comment by highhead** [comment] 2017-09-09 13:29
OK - I see!

Malden seems to have pretty few civilian buildings defined in the ALiVE index, so there definatly could be more buildings used. I'll change the topic to "Re-Index Malden"!

In the meanwhile I suggest the folling to work around it:

1. Set Civ placement setting to extreme
2. Set Civ placement filter to "do not filter"

Please try that

**Comment by nobodyshome** [comment] 2017-09-09 15:00
I tried what you suggested above and it has made a very little improvement, gone from 1-2 to about 5-10. Anything else I could try temporarily? Maybe specifying TOAR markers?

**Comment by highhead** [comment] 2017-09-09 15:49
As a dirty workaround you can use a CQB module, use faction CIV_F and put troop size to solo!

**Comment by friznit** [comment] 2017-09-17 10:08
Repro'd - issue is definitely with Malden.  I'll add to the backlog!

**Comment by marceldev89** [comment] 2017-09-19 08:51
Malden has been re-indexed in https://github.com/ALiVEOS/ALiVE.OS/commit/24818f3f2cdcfe0b27cfaacd7f1dfbd36a5a9932 :)

**Closed by marceldev89** 2017-09-19 08:51 UTC
Labels: Map Index, Task
