### ISSUE TITLE
CQB breaks initialization causing some units not to spawn on first attempt to play mission

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#295] opened 2017-02-24 05:16 UTC
I'm unsure if this is related to closed ticket #237 , but the civilian objective module can repeatedly and reliably fail to spawn units. One note I'd like to make on this, I have tried to repro this issue with vanilla off and on for over six months now (and can't). I have had this happen sporadically for a very long time now, with the only solution being building the mission from scratch. What I can say is that I can't trace this problem to any specific mod set, or combination of settings or modules. For example, although the example here is with RHS/Project OPFOR on Diyala, I have seen this using Massi units against 3CB on Reshmaan, where literally nothing is in common aside from CBA, ALiVE and Spyder Addons. And the reproduction steps are always the same, and always as strange.

1. Place the mission, unpacked, in your Missions folder in Documents and open in the SP editor
2. Press play and watch the civ obj spawns fail
3. Press esc and go back to the mission in the SP editor
4. Immediately press play on the mission again
5. Watch civ obj spawns succeed. It will now always succeed no matter how many times you hit esc and press play on the mission
6. Completely close down Arma 3
7. Open Arma and open the mission in the SP editor
8. Press play and watch civ obj spawns fail (rinse and repeat)

It will always fail on the first attempt and only fail on the first attempt.

Client rpt where I let it fail and then succeed: https://www.dropbox.com/s/j1kdjgeym8quo2g/Civ_obj_fail_Arma3_2017-02-23_23-44-56.rpt?dl=0

The mission: https://www.dropbox.com/s/ykz9akdk7051jzw/Oasis_of_Marah.DYA.pbo?dl=0

Required mods: CBA, ALiVE, Spyder Addons, RHS USAF, RHS AFRF, Project OPFOR, JBAD, Diyala Iraq

**Comment by HeroesandvillainsOS** [comment] 2017-02-25 04:08
And...and has always been the case with this bug, deleting the CQB module "fixes" it. I'm going to leave this open. It's plagued me for a long time now in around half a dozen different missions (of all flavors and varieties).

In the past, removing the CQB module and then adding it back usually keeps the issue fixed. For a while. Until it comes back.

I'm going to change the title to indicate CQB is breaking ALiVE's initialization under some circumstances.

**Comment by coachwn** [comment] 2017-02-25 04:42
We have had this happen sporadically as well. On our mission that is wrapping up tomorrow its not happened because we have rebuilt the mission almost once a week just to keep it fresh but in the previous missions we had issues with civs just disappearing after the server had been up for a few days straight.

**Comment by HeroesandvillainsOS** [comment] 2017-02-25 05:03
Thanks for the reply, Coachwn. I don't think what you're describing is similar to what's going on here though. Long story short, some unusual set of factors is causing the presence of the CQB module to cause obj module unit spawns to fail.

What I find odd about this, is that it only fails on the first attempt. Without closing the game, if you try to play the mission a second time, everything works as it should.

**Comment by coachwn** [comment] 2017-02-25 05:23
Hmmm yeah didn't track the first time. As I said we had that happen as the mission pushed on through instead of the other way round.

**Comment by highhead** [comment] 2017-02-26 21:25
fecking up on first start is typical initialsation issue. Thanks A3 due to it being a huge race condition. It doesnt have anything to do with CQB, its just getting obvious to it since it has an intense init that takes quite a while and slows down other parts of the init.

Try the following: delete ALL CQBs modules and Placement modules (Civ and Mil). Save the mission. Replace in the following order: CQB -> MIL MP -> MIL CP. Then save and run the mission (freshly booted). Will work pretty well...

**Comment by HeroesandvillainsOS** [comment] 2017-02-26 22:07
Ah ok. That makes sense when you put it that way. So does Arma 3 have some kind of caching system then, to ease the process of loading functions that have already loaded once on the 2+ attempts? 

I've "fixed" this in the past by deleting and replacing modules but since it keeps coming back I decided a ticket was necessary. I had no idea the order of module placement mattered at all so thanks for the tips, and I'll test this (and hopefully close the ticket) after CBA updates.

As alway, thanks Highhead.

**Comment by HeroesandvillainsOS** [comment] 2017-02-28 01:58
Highhead's solution works perfectly. Thanks man.

However, and I realize ticket solutions aren't designed to make you feel warm and fuzzy, but after doing the solution (deleting CQB and MIL/CIV Placement modules, saving, and then adding CQB, then MIL Placement, then CIV Placement and saving), if I edit the CQB module and save the mission again, the issue comes back. Which I guess doesn't surprise me, but I don't feel right closing this ticket.  

What do you guys think? Is it normal for mission makers to have to delete and replace all these modules anytime they get the urge to tinker something like the CQB module?  I realize you guys can't do anything about the order in which the mission.sqm saves data, but I release these publicly and get requests to edit things and I think it would be a real bummer to have to do this every time.

**Comment by SpyderBlack723** [comment] 2017-02-28 02:10
Are you completely going back to the editor or just hitting restart?

**Comment by HeroesandvillainsOS** [comment] 2017-02-28 04:06
I'm going completely back to the editor. So long story short, I launch the game and open the editor and press play on the mission (init fails). Exit back to the editor, press play again, and init succeeds. Doing Highhead's steps fixes the problem (init succeeds on the first attempt), but if I edit the CQB module, by let's say changing building percentages from 10% to 5 % and then saving the mission.sqm, it reverts back to always failing on the first attempt.

Good call on trying vanilla factions. I'll see what happens.

**Comment by HeroesandvillainsOS** [comment] 2017-02-28 04:49
It still fails on the first attempt after changing all the modules to vanilla factions (IND_F and BLU_F). The profile count is BLUFOR 37 vs IND 64 on the first attempt, and BLUFOR 71 vs IND 84 on the second attempt.

**Comment by SpyderBlack723** [comment] 2017-02-28 05:22
Well, I don't know how to explain that..

I can maybe find some time next week to try a few things.

**Comment by highhead** [comment] 2017-02-28 17:43
I assume that you will not be able to replicate that in vanilla...

Please can you do the following...
- Start Game
- Go into editor, open mission
- Turn on debug on, on all CIV placement modules AND on Virtual AI module
- Save and restart Arma 3
- Go into editor directly, open mission
- Directly start mission, let it complete and produce the error
- Hit restart, let it complete without that error
- Close game
- Upload RPT again

thanks

**Comment by HeroesandvillainsOS** [comment] 2017-02-28 18:06
Do you want me to use the ALiVE RC? The rpt will be a lot cleaner since it resolves the new #286 issue.

I agree I have not been able to reproduce this with a fresh vanilla mission, which sucks. I've tried. I have in the neighborhood of 10 missions now, which all at this point pretty much use identical mods, but only 2 of them are "infected" with this (my Inshallah mission suffers from it too). That said, I have been experiencing this off and on for quite awhile now. True, it's always with mods, but what's weird is that I've also had this happen in a 3CB and Massi mission, which leads me to believe this is ALiVE/Arma 3 related in some way, because I know it's not being caused by RHS/Project OPFOR, because that mission didn't use them.

Anyway, yeah man, I'll get you a fresh rpt and thanks for taking an interest in seeing what's up here. I do my very best these days not to post about issues when outside mods are involved but this one is killing me and I really don't think the mods are specifically to blame.

**Comment by HeroesandvillainsOS** [comment] 2017-03-01 03:20
Here's a fresh rpt. I decided to debug Virtual AI, and all MIL and CIV Placement modules just to cover my bases: https://www.dropbox.com/s/dhp00kg9bqt2fqz/init_fail_Arma3_2017-02-28_22-09-09.rpt?dl=0

**Comment by highhead** [comment] 2017-03-01 14:41
Thanks! In the whole RPT there is no single CP instance that does NOT create any profiles:

22:10:51 ALiVE [m_13|100] Module ALiVE_civ_placement INIT
22:10:51 ----------------------------------------------------------------------------------------
22:10:57 ALIVE CP - Placement
22:10:57 [TIMER STARTED]
22:10:57 ALIVE CP [LOP_ISTS] - Size: 100 Type: Infantry SideNum: 2 Side: GUER Faction: LOP_ISTS
22:10:57 ALIVE CP [LOP_ISTS] - Size: 100
22:10:57 ALIVE CP [LOP_ISTS] - Main force creation 
22:10:57 Count Armor: 0
22:10:57 Count Mech: 0
22:10:57 Count Motor: 0
22:10:57 Count Air: 0
22:10:57 Count Infantry: 8
22:10:57 Count Spec Ops: 2
22:10:57 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_45]
22:10:57 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_46]
22:10:57 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_47]
22:10:57 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_48]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_49]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_50]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_51]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_52]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_53]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_54]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_55]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_56]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_57]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_58]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_59]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_60]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_61]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_62]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_63]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_64]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_65]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_66]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_67]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_68]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_69]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_70]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_71]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_72]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_73]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_74]
22:10:58 ALIVE CP - Total profiles created: 8
22:10:58 ALIVE CP - Placement completed
22:10:58 [TIMER ENDED : 0.204002]
22:10:58 ----------------------------------------------------------------------------------------
22:10:58 ALiVE [m_13|100] Module ALiVE_civ_placement INIT COMPLETE TIME:  6.36

etc....

**Comment by highhead** [comment] 2017-03-01 14:44
can you see those profiles on the map after init?

f.e. 22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_61]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_62]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_63]
22:10:58 ALIVE Profile Handler - Register Profile [LOP_ISTS-entity_64]

they look like e61, e62 etc. on the map.

**Comment by HeroesandvillainsOS** [comment] 2017-03-01 15:37
I'll take a look later. Sorry if there was confusion with my description of the problem. It's not that profiles aren't spawning, or that there's any tangible errors, it's that profiles are not spawning in the correct amounts on the first attempt to play the mission(s). Something is preventing the profiles from spawning in full (and it seems to me it's the CIV Placement but I'm not 100% on that).

Example: 
Attempt 1 BLU: 37 vs IND 64
Attempt 2 BLU: 74 vs IND 80

Those are just approximations. But you can see how this is not ideal when playing as BLU and only have access to half of your operational groups.

I'll take a look later on to see if they're showing up. Thanks for looking at the rpt man.

**Comment by highhead** [comment] 2017-03-01 15:48
ahhhhhhh my bad. sorry - I got it wrong. So it maybe that some of the CPs or some objectives assigned to the CPs are not initialising.

22:10:51 ALiVE [m_13|100] Module ALiVE_civ_placement INIT
22:10:58 ALIVE CP - Total profiles created: 8
22:10:58 ALIVE CP - Placement completed
22:10:58 [TIMER ENDED : 0.204002]
22:10:58 ----------------------------------------------------------------------------------------
22:10:58 ALiVE [m_13|100] Module ALiVE_civ_placement INIT COMPLETE TIME:  6.36

22:10:51 ALiVE [m_10|100] Module ALiVE_civ_placement INIT
22:10:58 ALIVE CP - Total profiles created: 10
22:10:58 ALIVE CP - Placement completed
22:10:58 [TIMER ENDED : 0.209]
22:10:58 ----------------------------------------------------------------------------------------
22:10:58 ALiVE [m_10|100] Module ALiVE_civ_placement INIT COMPLETE TIME:  6.968

22:14:03 ALiVE [m_46|100] Module ALiVE_civ_placement INIT
22:14:04 ALIVE CP - Total profiles created: 8
22:14:04 ALIVE CP - Placement completed
22:14:04 [TIMER ENDED : 0.205994]
22:14:04 ----------------------------------------------------------------------------------------
22:14:04 ALiVE [m_46|100] Module ALiVE_civ_placement INIT COMPLETE TIME:  0.462006

22:14:04 ALiVE [m_47|100] Module ALiVE_civ_placement INIT
22:14:04 ALIVE CP - Total profiles created: 8
22:14:04 ALIVE CP - Placement completed
22:14:04 [TIMER ENDED : 0.189972]
22:14:04 ----------------------------------------------------------------------------------------
22:14:04 ALiVE [m_47|100] Module ALiVE_civ_placement INIT COMPLETE TIME:  0.587982

...there are no more inits of any other CP modules. Can you confirm 4 CP modules?

Furthermore, please turn on debug of CP modules and look for "changing" objectives on map, esp. if objective markers are missing!

**Comment by HeroesandvillainsOS** [comment] 2017-03-01 17:50
This mission gives each OPCOM 1 MIL and 1 CIV Obj Placement module. So yes, 4 in total (2 CIV, 2 MIL). And a bunch of Cust Obj for each. I'll take a couple screens to compare to see if it's obvious what/where obj's aren't spawning.

**Comment by HeroesandvillainsOS** [comment] 2017-03-02 01:43
Ok so here are some photos. That was a good idea dude because you can see pretty clearly that some MIL Obj's (and I think cust obj's too) are failing. Notice on the right side of the screen in the fail one how some yellow military obj markers don't appear. I can't quite tell based on the phots if any CIV Obj's are failing, but it wouldn't surprise me (sorry to use dropbox but imgur is down right now):

Success: https://www.dropbox.com/s/az7ci4wnk8tcsqu/succeed.jpg?dl=0
Fail: https://www.dropbox.com/s/ttfb79w7pw0qwk3/fail.jpg?dl=0

And no, the missing units aren't showing up on the map at all. They never spawn. I think you're right about something causing objectives themselves to fail to init.

**Comment by highhead** [comment] 2017-03-03 12:19
Yo mate!

Thats strange: According to the log above there must be 4 (!) CIV placement modules not 2 CIV and 2 MIL but 4 CIV!

we are getting closer....

**Comment by highhead** [comment] 2017-03-03 12:19
MIL would be ALiVE_mil_placement

**Comment by HeroesandvillainsOS** [comment] 2017-03-03 15:23
Lol! Strange! I mean, they're definitely MIL. I can show you a screenie if you want (though I'm sure you believe me). Is there anything I can do from here so we can keep making progress on this?

**Comment by highhead** [comment] 2017-03-04 11:15
I am afraid not without me downloading all the mods so I can run your mission....

Can you gimme a list of mods thats needed for that mission? please no more than really needed...

**Comment by HeroesandvillainsOS** [comment] 2017-03-04 15:49
Yeah sure. They're all on Workshop if that helps.

CBA
ALiVE
Spyder Addons
RHS USAF
RHS AFRF
Project OPFOR
JBAD
Diyala Province Iraq

Download link:

https://www.dropbox.com/s/ykz9akdk7051jzw/Oasis_of_Marah.DYA.pbo?dl=0

**Comment by HeroesandvillainsOS** [comment] 2017-03-06 15:31
No hurry on downloading the mods/mission, but just wanted to say I'm getting this issue in a brand new mission as well. One of my guesses was that this was some kind of backwards compatibility problem for missions started with older ALiVE versions (I began making and maintaining Oasis of Marah several months ago), but it's definitely not that.

**Comment by highhead** [comment] 2017-03-07 19:09
this mission weights impressive 22 (! twentytwo !) Megabytes lol

**Comment by HeroesandvillainsOS** [comment] 2017-03-07 19:17
17 or so of those MB's are due to AuTigerGrad's Ambient sound pack. It has nothing to do with scripts or objects or general content. 

I don't blame you for being curious about why it's so large. I would have wondered too because I agree it's unusual at first glance.

**Comment by HeroesandvillainsOS** [comment] 2017-03-07 19:20
^^^ I'm not denying I don't place a lot of objects though (to make my bases look interesting). I do and probably shouldn't. Makes me wonder whether this is what's causing the issue TBH because I'm stumped otherwise.

**Comment by highhead** [comment] 2017-03-07 19:20
20:12:07   rhsusf_c_m252
20:12:07   rhsusf_c_mrzr
20:12:07   rhsusf_c_RG33L

 is missing... its also missing from their ftp... so I cannot open the mission properly without manipulating it

guess I need to redownload it from workshop (again)

**Comment by HeroesandvillainsOS** [comment] 2017-03-07 19:28
You're using the Workshop versions of RHS AFRF (Russia), USAF (USA) and Project OPFOR? That's all the mission would need faction-wise.

**Comment by highhead** [comment] 2017-03-07 19:31
nah I had RHS installed and used the wget updater, but its prolly outdated since steam workshop DL

**Comment by HeroesandvillainsOS** [comment] 2017-03-07 19:33
The wget updater I believe is no longer supported. Only Workshop is officially supported, and the mirrors are at the mercy of Armaholic and (ugh) PWS (which is HORRIBLE for reliably updating files). I use Workshop for everything if it's available.

**Comment by highhead** [comment] 2017-03-07 20:43
OK I managed to DL all the needed addons. Seems like I cannot reproduce any issue with your mission and our latest dev branch and A3 RC.

I am always getting between 80 profiles now on average, evenly spread to BLU and IND:

fresh: 76 vs. 79
restart: 87 vs. 83

fresh: 82 vs. 84
restart: 79 vs. 77

fresh: 85 vs. 82
restart: 80 vs. 76

I assume its because of these commits, which fix an issue with ALiVE not initialising properly:
https://github.com/ALiVEOS/ALiVE.OS/commit/de0e96f0473c65e966d3a553c156c9f7e239e2d3 (this fix is for Single Player / Editor use only; I commited another change that fixes the same for all localities)

The commit above is present in this pre-release of 20-02-2017: https://github.com/ALiVEOS/ALiVE.OS/releases/tag/v1.3.0.1702201

Can you please try, if this version fixes the init issue?

**Comment by highhead** [comment] 2017-03-07 20:44
PS: in your rpt I saw you was using the version of 19-01-2017 I believe

**Comment by highhead** [comment] 2017-03-07 20:46
PPS: Also there is no issues with the modules, I prolly put two parts of the rpt together, the mission looks really good! They also do not have vanishing objectives!

**Comment by HeroesandvillainsOS** [comment] 2017-03-07 20:53
Wow! That's good hear. Though keep in mind, the version I sent you would probably need you to mess around with something like the CQB module to duplicate this issue.

Example: open editor. Change CQB from 5% to 2% (or 10%). Save. Close game. Open the mission and press play. 

Did you tinker with the modules at all?

I'll try the RC and see how it goes. And thanks again for your efforts. It means a lot. This problem has been nagging me for quite some time in various missions, so I don't "play" ALiVE as much as I'd like right now, and tend to just play with the systems in the editor. So I really do want to thank you for all the time you've spent with me on this.

**Comment by highhead** [comment] 2017-03-07 20:54
nope I assumed the issue would be replicable by running it straight on a fresh client (noting the low count) and then restarting it (noting the high count).

please try to replicate the issue with the version above, but I guess it will be fixed (hoperfully) :)

**Comment by HeroesandvillainsOS** [comment] 2017-03-07 20:55
Oh haha thanks for complimenting the mission. I usually make insurgencies but Diyala (since it doesn't really spawn civs. No idea why) seemed perfect for a sandbox op task-based scenario against ISIS. :)

**Comment by HeroesandvillainsOS** [comment] 2017-03-07 20:55
Will do. I appreciate it.

**Comment by highhead** [comment] 2017-03-07 20:56
cool, tried again and lowest I got was

21:55:14  ------------------ Inspecting Hash -------------------- 
21:55:14    k [0]: EAST v: []
21:55:14    k [1]: WEST v: ["player_0","entity_1","vehicle_3","vehicle_4","vehicle_5","vehicle_6","rhs_faction_usarmy_d-entity_13","rhs_faction_usarmy_d-entity_14","rhs_faction_usarmy_d-vehicle_7","rhs_faction_usarmy_d-vehicle_8","rhs_faction_usarmy_d-vehicle_9","rhs_faction_usarmy_d-vehicle_10","rhs_faction_usarmy_d-entity_15","rhs_faction_usarmy_d-entity_16","rhs_faction_usarmy_d-vehicle_11","rhs_faction_usarmy_d-vehicle_12","rhs_faction_usarmy_d-vehicle_13","rhs_faction_usarmy_d-vehicle_14","rhs_faction_usarmy_d-entity_18","rhs_faction_usarmy_d-vehicle_15","rhs_faction_usarmy_d-vehicle_16","rhs_faction_usarmy_d-vehicle_17","rhs_faction_usarmy_d-vehicle_18","rhs_faction_usarmy_d-entity_19","rhs_faction_usarmy_d-entity_20","rhs_faction_usarmy_d-vehicle_19","rhs_faction_usarmy_d-vehicle_20","rhs_faction_usarmy_d-vehicle_21","rhs_faction_usarmy_d-vehicle_22","rhs_faction_usarmy_d-entity_21","rhs_faction_usarmy_d-entity_22","rhs_faction_usarmy_d-vehicle_23","rhs_faction_usarmy_d-vehicle_24","rhs_faction_usarmy_d-vehicl
21:55:14    k [2]: GUER v: ["entity_0","vehicle_0","vehicle_1","vehicle_2","LOP_ISTS-entity_3","LOP_ISTS-entity_7","LOP_ISTS-entity_8","LOP_ISTS-entity_9","LOP_ISTS-entity_10","LOP_ISTS-entity_12","LOP_ISTS-entity_31","LOP_ISTS-entity_32","LOP_ISTS-entity_33","LOP_ISTS-entity_34","LOP_ISTS-entity_35","LOP_ISTS-entity_36","LOP_ISTS-entity_37","LOP_ISTS-entity_38","LOP_ISTS-entity_39","LOP_ISTS-entity_40","LOP_ISTS-entity_41","LOP_ISTS-entity_42","LOP_ISTS-entity_43","LOP_ISTS-entity_44","LOP_ISTS-entity_47","LOP_ISTS-entity_48","LOP_ISTS-entity_49","LOP_ISTS-entity_50","LOP_ISTS-entity_51","LOP_ISTS-entity_52","LOP_ISTS-entity_56","LOP_ISTS-entity_57","LOP_ISTS-entity_58","LOP_ISTS-entity_59","LOP_ISTS-entity_60","LOP_ISTS-entity_61","LOP_ISTS-entity_65","LOP_ISTS-entity_66","LOP_ISTS-entity_67","LOP_ISTS-entity_68","LOP_ISTS-entity_69","LOP_ISTS-entity_70","LOP_ISTS-entity_71","LOP_ISTS-entity_72","LOP_ISTS-entity_74","LOP_ISTS-entity_75","LOP_ISTS-entity_76","LOP_ISTS-entity_77","LOP_ISTS-entity_78","LOP_ISTS-entity
21:55:14    k [3]: CIV v: []
21:55:14  ------------------ Inspection Complete -------------------- 
21:55:14 0
21:55:14 74
21:55:14 71
21:55:14 0

**Comment by HeroesandvillainsOS** [comment] 2017-03-07 21:05
Looks good to me. I'll grab the RC later tonight (which is shameful that I don't already have it as we speak. CQB turrets on rooftops baby!) and see if I have the same luck.

**Comment by HeroesandvillainsOS** [comment] 2017-03-08 03:06
Ok so I started the mission around a dozen+ times with the RC, occasionally editing CQB and saving and relaunching the game, and the "worst" deviation I saw was 63 vs 83. Most of them were a lot more similar to what you saw (78 vs 80, etc).

Aside from that, the objective warning on mission start would sometimes tell me LOP_ISTS had 87 objectives, and other times 89. But all in all I feel that this is all normal now, within the normal deviation, and initializing as one would expect.

Does all this seem normal to you? If so, I'll close the ticket. And very sorry to have you chase your tail on this. If had had even a remote suspicion you had already fixed this in RC, I would have tested it first.

**Comment by SpyderBlack723** [comment] 2017-03-08 03:29
differing objective numbers is worrysome. I'm guessing if it just differs by two, then it's probably custom objectives having issues?

**Comment by HeroesandvillainsOS** [comment] 2017-03-08 04:26
I am using quite a few custom objectives to fill in the gaps (I was stuck in a situation where tiny was spawning too many objectives, and small wasn't spawning enough). Most of the custom objectives are set to spawn with units but a few are objectives only. And most of them are synced to both commanders, but all of them have only one side defined in the custom obj module.

If you guys need me to remove them and test again I can do that.

Highhead since you have the mission downloaded, maybe you can take a peak at the cust obj's and see if this deviation would make sense on init?

**Comment by highhead** [comment] 2017-03-08 19:55
cool that its working now. or at least better. I agree that the mission as a masssssssive amount of cust. obj.! BIS has done an awesome job with module_f init (i put up a ticket long ago but it vanished completely from the webs, cannot find it anymore), so it may really be an issue if there are too many modules are placed in some maps. Actually if I may suggest to just reduce them to some numbers (maybe 2?) would solve the issue. Please try that, comrade!

If it doesnt work please reopen the ticket!

**Closed by highhead** 2017-03-08 19:55 UTC
Labels: bug, Needs Repro

**Comment by HeroesandvillainsOS** [comment] 2017-03-08 20:37
I should only use two custom objectives when I make missions in general? Or were you suggesting this just to test?

Anyway, your commit definitely gives me results I can play happily with so I feel good with this ticket being closed. Thanks for all the help Highead.

**Comment by highhead** [comment] 2017-03-10 14:35
Trololol!

no :) not only 2 custom objectives :)

I meant reduce the (sheer endless) amount of custom obj. by 2 objectives since the init seems to fail on 2 objectives randomly, so this could be the "sweet spot" for your mission!

Sorry if I have been unclear! Thanks for your hard work with reporting all that shizzle mate!

**Comment by HeroesandvillainsOS** [comment] 2017-03-10 16:12
Oh haha. Yeah that makes more sense. Thanks for all the hard work Highhead.

**Comment by HeroesandvillainsOS** [comment] 2017-03-29 16:29
@highhead Good call on deleting the cust objs. I deleted all of the handcrafted and editor placed custom objs and with a bit of finagling, was able to get a 70v70 battle going with just the normal mil/civ objs and I'm much happier now all around. Thanks man.

**Comment by highhead** [comment] 2017-03-29 17:07
It's great, that you got it working as desired! I know - fine tuning can be a hard job but its really worth it! Happy to help if you need it ofc :)

**Comment by HeroesandvillainsOS** [comment] 2017-03-29 17:36
Well if you're ever bored, and certainly no hurry whatsoever, but some insurgency balancing tips would be helpful. Still having a hard time keeping the civ recruitment numbers in check even using large-ish min civ recruitment numbers.

http://alivemod.com/forum/2840-insurgency-balancing-tips/0#p19461

Again, NO HURRY. Even if it's like a month from now and you have a second to pop in, that would be fine. I know you're a busy person. And thanks so much for all the support! You've helped me a lot the last few months and it means a lot. :)
