### ISSUE TITLE
Orbatterer: odd behaviour when equipping NVGs

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#105] opened 2016-09-30 17:15 UTC
From [ze forum](https://forums.bistudio.com/topic/187954-alive-advanced-light-infantry-virtual-environment-10-ga/page-44#entry3098696)

> With the ORBAT- I'm having a really weird bug with NVG's at the moment- if I give a unit NVG's they appear on his head for a moment before disappearing in the loadout creator- Upon testing the faction I found that the NVG's were being teleported the soldiers uniform inventory, filling that with 2-3 copies of NVG's, which is hilarious, but not helpful, so I have removed NVG's from all my factions for the time being- any ideas as to cause?

**Comment by 1ncontinentia** [comment] 2016-09-30 17:45
This is common behaviour with ASR AI, just in case that hasn't been considered yet.

**Comment by SpyderBlack723** [comment] 2016-09-30 18:34
Yeah, this is due to ASR. Not sure if there is a way to disable..

**Comment by 1ncontinentia** [comment] 2016-09-30 18:39
I think there's an option in the settings somewhere about packing NVGs during daytime?

**Comment by SpyderBlack723** [comment] 2016-09-30 18:49
I suggested simply disabling ASR, as it's not going to be in use whole using this module anway.

Closing as behavior is caused by 3rd party mos.

**Closed by SpyderBlack723** 2016-09-30 18:49 UTC
Labels: bug, Needs Repro
