### ISSUE TITLE
[CivilianPopulation] Civilians stack in formation ot the group and vehicles explode everytime

### ISSUE THREAD

**Issue by shukari** [ALiVEOS/ALiVE.OS#277] opened 2017-02-01 16:35 UTC
I made a example stress test for one of my missions... i would like to have a full living city that use the virtual profiling system because of performance...
But my tests are really bad... the civilians run around (dont walk or stand still) and stack at the group leader.
Also the vehicles are placed on the street (i dont know if it is possible to place them on the side if the road) or in the garden... OR the explode (tried it 10 times 10 times min one vehicle exploded) OR it will bug in houses...

I really hope you can optimise this a little bit ^^
Big thanks for this nice mod ;D

Stratis StressTestRepo: http://workupload.com/file/zgz2Ajh
Altis StressTestRepo: https://workupload.com/file/7wxheYP

**Comment by highhead** [comment] 2017-02-02 19:16
thanks for the repro missions, ill give them a shot!

**Comment by highhead** [comment] 2017-02-02 19:18
btw. I can confirm exploding lots of civi vehicles on Tanoa too. seems the vehicle placement is broken!

**Comment by highhead** [comment] 2017-02-04 23:23
this is fixed in master, will be deployed soon(tm)! exploding vehicles is fixed in #281

**Comment by highhead** [comment] 2017-02-04 23:25
PS: Be aware that civis like to meet up and party, so you may come across a pile of dudes hanging around. Sometimes may look a bit funny, but this is intended (until we are on to simulting crowds and protesters).

**Comment by wolffy-au** [comment] 2017-02-05 04:16
![singlecivgroup](https://cloud.githubusercontent.com/assets/25105266/22623601/e9b68ff6-ebb4-11e6-898a-931f031c6d89.gif)
[singleCivGroup.rpt.txt](https://github.com/ALiVEOS/ALiVE.OS/files/752743/singleCivGroup.rpt.txt)
![master](https://cloud.githubusercontent.com/assets/25105266/22623622/5d6e5fdc-ebb5-11e6-9103-6b39c84a526c.gif)
[master.rpt.txt](https://github.com/ALiVEOS/ALiVE.OS/files/752745/master.rpt.txt)

Did some testing. The grouping seems to occur, but not around the leader. There is much less activity in the Master example (implies less likely chance to form "gathering"). Report sizes are 700 lines difference of action debug events. Thoughts?

**Closed** 2017-02-05 11:46 UTC
