### ISSUE TITLE
Transport helicopters refuse to land.

### ISSUE THREAD

**Issue by EasyEB** [ALiVEOS/ALiVE.OS#99] opened 2016-09-19 15:35 UTC
Not always.

But often, transport helicopters refuse to land when ordered to. Instead they get dip down, change their mind about the spot, shuffle a bit and then dips down again. Rinse repeat.

**Comment by SpyderBlack723** [comment] 2016-09-19 15:46
From reports on the forums, it seems this is an issue/conflict with VCOM AI. Are you perhaps running this mod/script?

**Comment by EasyEB** [comment] 2016-10-05 19:42
RHS Black Hawks tend to never land, RHS Little Birds, Mi-8s, CH-47s rarely (Little Bird never) have any problem touching down.

**Comment by SpyderBlack723** [comment] 2016-11-08 21:16
Any updates on this? Are you still encountering this issue?

**Comment by marceldev89** [comment] 2016-11-08 22:47
Played with the RHS Black Hawks (as combat support assets) a couple of days ago and they landed fine when I told them to. Cannot reproduce on my end, so far.

**Comment by tupolov** [comment] 2016-11-08 23:25
I've seen issues with Helo's landing after they have been given a slingloading task. This is usually down to the fact the helo is still "stuck" on an UNHOOK waypoint. We fixed this a few releases back though.

**Comment by friznit** [comment] 2016-12-12 11:36
Tested with multiple different mods and helis, cannot repro.

**Closed by friznit** 2016-12-12 11:36 UTC
Labels: Needs Repro
